import { User, Siswa, Guru, Kelas, MataPelajaran, JadwalPelajaran, PresensiRecord, NilaiSiswa, TagihanSPP, JenisTagihan, Pengumuman, SchoolProfile, TabunganSiswa, TransaksiTabungan, PesertaTransportasi, RecordSPPTransportTahunAjaran, TransaksiSPPTransport, BulanSPP, LMSMateri, LMSTugas, LMSSubmission, LMSKuis, LMSKuisAttempt, LMSForumDiskusi, LMSVirtualMeeting, LMSBankSoal, LMSJadwalMateri, SurahJuz30Info, TahfidzRecord, MutabaahRecord } from "@/types/school";

export const INITIAL_SCHOOL_PROFILE: SchoolProfile = {
  namaSekolah: "SMA Plus Nusantara & SDI Smart School",
  npsn: "20108924",
  akreditasi: "A (Unggul)",
  alamat: "Jl. Pendidikan Cendekia No. 45, Kebayoran Baru, Jakarta Selatan",
  telepon: "(021) 7890-1234",
  email: "info@smanusantara.sch.id",
  website: "https://smanusantara.sch.id",
  kepalaSekolah: "Dr. H. Muhammad Rasyid, M.Pd.",
  tahunAjaranAktif: "2025/2026",
  semesterAktif: "Ganjil",
  appName: "SIM Sekolah PRO",
  appTagline: "Sistem Informasi Manajemen Sekolah Terpadu",
  appLogoUrl: "",
  appIconPreset: "graduation",
  landingHeroBadge: "Platform Manajemen Sekolah Generasi Terbaru #1",
  landingHeroTitle: "Transformasi Digital Pendidikan yang Cerdas, Efisien & Terpadu",
  landingHeroSubtitle: "Kelola seluruh ekosistem sekolah dari administrasi siswa, tenaga pendidik, absensi digital, e-rapor, hingga tagihan SPP dalam satu platform modern berkecepatan tinggi.",
  landingCtaText: "Buka Portal & Form Login",
  landingShowDemoButton: true,
  landingFooterText: "SIM Sekolah PRO - Sistem Informasi Manajemen Sekolah Terpadu. All rights reserved.",
  // Multi-Unit / Yayasan
  namaYayasan: "Yayasan Pendidikan Islam Cendekia Nusantara",
  jenjangSekolah: "SDI & SMP Terpadu",
  nomorIzinOperasional: "421.2/1089-Disdik/2021",
  // WhatsApp Gateway Defaults
  waGatewayProvider: "fonnte",
  waAutoSendPresensiMasuk: true,
  waAutoSendPresensiPulang: true,
  waAutoSendSPP: true,
  waTemplatePresensi: "Assalamu'alaikum Wr. Wb. Diberitahukan bahwa ananda *{nama}* (Kelas {kelas}) telah tercatat *{status}* pada jam {waktu} WIB ({tanggal}). Terima kasih.",
  waTemplateSPP: "Assalamu'alaikum Wr. Wb. Terima kasih, pembayaran *{judul}* ananda *{nama}* (Kelas {kelas}) sebesar *Rp {nominal}* telah kami terima dengan No. Kuitansi: *{kuitansi}*. Status: *LUNAS*.",
  // Payment Gateway Defaults
  paymentProvider: "midtrans",
  midtransIsProduction: false,
};

export const DEMO_USERS: User[] = [
  {
    id: "usr-1789900657053-35",
    name: "Rizki XP",
    email: "rizkixp@gmail.com",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rizki",
    phone: "0812-3456-7890",
    status: "Aktif",
    password: "admin123",
    createdAt: "2026-09-20",
  },
  {
    id: "usr-efelfori",
    name: "Efelfori",
    email: "efelfori@gmail.com",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Efelfori",
    phone: "0812-9988-7766",
    status: "Aktif",
    password: "admin123",
    createdAt: "2026-09-26",
  },
  {
    id: "usr-admin",
    name: "Dr. H. Muhammad Rasyid, M.Pd.",
    email: "admin@sekolah.id",
    role: "admin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "197204151998031002",
    phone: "0812-3456-7890",
    status: "Aktif",
    password: "admin123",
    createdAt: "2024-01-01",
  },
  {
    id: "usr-bendahara",
    name: "Hj. Endang Rahmawati, S.E. (Bendahara)",
    email: "bendahara@sekolah.id",
    role: "bendahara",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "198802142012012003",
    phone: "0813-8899-7766",
    status: "Aktif",
    password: "bendahara123",
    createdAt: "2024-01-10",
  },
  {
    id: "usr-guru",
    name: "Siti Nurhaliza, S.Pd., M.Si.",
    email: "guru@sekolah.id",
    role: "guru",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "198506122010012015",
    kelas: "X MIPA 1",
    phone: "0813-9876-5432",
    status: "Aktif",
    password: "guru123",
    createdAt: "2024-01-05",
  },
  {
    id: "usr-guru-ratna",
    name: "Hj. Ratna Dewi, S.Pd.I., M.Ag.",
    email: "ratna.dewi@sekolah.id",
    role: "guru",
    avatar: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "199004082015042008",
    kelas: "X MIPA 2",
    phone: "0856-7788-9900",
    status: "Aktif",
    password: "guru123",
    createdAt: "2024-01-05",
  },
  {
    id: "usr-guru-ferry",
    name: "Ferry Irawan, S.Pd.",
    email: "ferry.irawan@sekolah.id",
    role: "guru",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "199201182018011002",
    kelas: "XI IPS 1",
    phone: "0877-5544-3322",
    status: "Aktif",
    password: "guru123",
    createdAt: "2024-01-05",
  },
  {
    id: "usr-guru-dewi",
    name: "Dewi Kurniasih, S.Si., M.Pd.",
    email: "dewi.kurniasih@sekolah.id",
    role: "guru",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "198309102008012019",
    kelas: "XII MIPA 1",
    phone: "0812-4455-6677",
    status: "Aktif",
    password: "guru123",
    createdAt: "2024-01-05",
  },
  {
    id: "usr-guru-kelas6",
    name: "Ahmad Fauzi, S.Pd.I. (Guru Kelas 6)",
    email: "guru.kelas6@sekolah.id",
    role: "guru",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "198711052011011003",
    kelas: "Kelas 6",
    phone: "0813-2233-4477",
    status: "Aktif",
    password: "guru123",
    createdAt: "2024-01-05",
  },
  {
    id: "usr-siswa",
    name: "Ahmad Rizky Pratama",
    email: "siswa@sekolah.id",
    role: "siswa",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "0078129034",
    kelas: "X MIPA 1",
    phone: "0857-1122-3344",
    status: "Aktif",
    password: "siswa123",
    createdAt: "2024-07-10",
  },
  {
    id: "usr-ortu",
    name: "Ir. Bambang Sudirman (Wali Rizky)",
    email: "ortu@sekolah.id",
    role: "ortu",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    nisnOrNip: "0078129034",
    kelas: "X MIPA 1",
    phone: "0811-2233-4455",
    status: "Aktif",
    password: "ortu123",
    createdAt: "2024-07-10",
  },
];

export const INITIAL_SISWA: Siswa[] = [
  {
    id: "sis-001",
    nisn: "0078129034",
    nama: "Ahmad Rizky Pratama",
    jenisKelamin: "L",
    kelas: "X MIPA 1",
    jurusan: "MIPA",
    tanggalLahir: "2008-04-12",
    tempatLahir: "Jakarta",
    alamat: "Jl. Melati No. 12, Kebayoran Baru",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-002",
    nisn: "0078129035",
    nama: "Anisa Zahra Humaira",
    jenisKelamin: "P",
    kelas: "X MIPA 1",
    jurusan: "MIPA",
    tanggalLahir: "2008-08-25",
    tempatLahir: "Bandung",
    alamat: "Jl. Cendrawasih No. 5, Jaksel",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-003",
    nisn: "0078129036",
    nama: "Bima Arya Putra",
    jenisKelamin: "L",
    kelas: "X MIPA 1",
    jurusan: "MIPA",
    tanggalLahir: "2008-02-14",
    tempatLahir: "Bogor",
    alamat: "Jl. Dahlia Indah Blok C3, Jakarta",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-004",
    nisn: "0078129037",
    nama: "Dewi Lestari Kusuma",
    jenisKelamin: "P",
    kelas: "X MIPA 2",
    jurusan: "MIPA",
    tanggalLahir: "2008-11-03",
    tempatLahir: "Surabaya",
    alamat: "Jl. Panglima Polim No. 78",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-005",
    nisn: "0078129038",
    nama: "Fajar Nugraha",
    jenisKelamin: "L",
    kelas: "XI IPS 1",
    jurusan: "IPS",
    tanggalLahir: "2007-06-19",
    tempatLahir: "Jakarta",
    alamat: "Jl. Fatmawati Raya No. 102",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-006",
    nisn: "0078129039",
    nama: "Nabila Aulia Rahmah",
    jenisKelamin: "P",
    kelas: "XI IPS 1",
    jurusan: "IPS",
    tanggalLahir: "2007-09-09",
    tempatLahir: "Semarang",
    alamat: "Jl. Ampera Raya No. 23",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-007",
    nisn: "0078129040",
    nama: "Muhammad Kevin Ardiansyah",
    jenisKelamin: "L",
    kelas: "XII MIPA 1",
    jurusan: "MIPA",
    tanggalLahir: "2006-03-30",
    tempatLahir: "Medan",
    alamat: "Jl. Kemang Timur No. 44",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "sis-008",
    nisn: "0078129041",
    nama: "Tiara Safitri",
    jenisKelamin: "P",
    kelas: "XII MIPA 1",
    jurusan: "MIPA",
    tanggalLahir: "2006-12-15",
    tempatLahir: "Jakarta",
    alamat: "Jl. Cipete Raya No. 19",
    namaWali: "",
    noHpWali: "",
    status: "Aktif",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_GURU: Guru[] = [
  {
    id: "gur-001",
    nip: "198506122010012015",
    nama: "Siti Nurhaliza",
    gelar: "S.Pd., M.Si.",
    jenisKelamin: "P",
    mataPelajaran: ["Matematika Wajib", "Matematika Peminatan"],
    kelasWali: "X MIPA 1",
    pendidikanTerakhir: "S2 Pendidikan Matematika - UPI",
    statusKepegawaian: "PNS",
    email: "guru@sekolah.id",
    noHp: "0813-9876-5432",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "gur-002",
    nip: "197802152003121004",
    nama: "Drs. Eko Prasetyo",
    gelar: "M.Pd.",
    jenisKelamin: "L",
    mataPelajaran: ["Fisika"],
    kelasWali: "XI MIPA 2",
    pendidikanTerakhir: "S2 Manajemen Pendidikan - UNJ",
    statusKepegawaian: "PNS",
    email: "eko.prasetyo@sekolah.id",
    noHp: "0812-1122-3344",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "gur-003",
    nip: "199004082015042008",
    nama: "Hj. Ratna Dewi",
    gelar: "S.Pd.I., M.Ag.",
    jenisKelamin: "P",
    mataPelajaran: ["Pendidikan Agama Islam", "Bahasa Arab"],
    kelasWali: "X MIPA 2",
    pendidikanTerakhir: "S2 Studi Islam - UIN Jakarta",
    statusKepegawaian: "Tetap Yayasan",
    email: "ratna.dewi@sekolah.id",
    noHp: "0856-7788-9900",
    avatar: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "gur-004",
    nip: "199201182018011002",
    nama: "Ferry Irawan",
    gelar: "S.Pd.",
    jenisKelamin: "L",
    mataPelajaran: ["Bahasa Inggris"],
    kelasWali: "XI IPS 1",
    pendidikanTerakhir: "S1 Pendidikan Bahasa Inggris - UI",
    statusKepegawaian: "Honorer",
    email: "ferry.irawan@sekolah.id",
    noHp: "0877-5544-3322",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "gur-005",
    nip: "198309102008012019",
    nama: "Dewi Kurniasih",
    gelar: "S.Si., M.Pd.",
    jenisKelamin: "P",
    mataPelajaran: ["Biologi", "Kimia"],
    kelasWali: "XII MIPA 1",
    pendidikanTerakhir: "S2 Pendidikan IPA - ITB",
    statusKepegawaian: "PNS",
    email: "dewi.kurniasih@sekolah.id",
    noHp: "0818-6677-8811",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "gur-006",
    nip: "198711052011011003",
    nama: "Ahmad Fauzi",
    gelar: "S.Pd.I.",
    jenisKelamin: "L",
    mataPelajaran: ["Tematik", "Matematika", "Pendidikan Agama Islam"],
    kelasWali: "Kelas 6",
    pendidikanTerakhir: "S1 PGSD / Tarbiyah - UIN Jakarta",
    statusKepegawaian: "PNS",
    email: "guru.kelas6@sekolah.id",
    noHp: "0813-2233-4477",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_KELAS: Kelas[] = [
  {
    id: "cls-01",
    nama: "X MIPA 1",
    tingkat: "X",
    waliKelasId: "gur-001",
    waliKelasNama: "Siti Nurhaliza, S.Pd., M.Si.",
    kapasitas: 36,
    jumlahSiswa: 34,
    ruangan: "Gedung A - R. 101",
  },
  {
    id: "cls-02",
    nama: "X MIPA 2",
    tingkat: "X",
    waliKelasId: "gur-003",
    waliKelasNama: "Hj. Ratna Dewi, S.Pd.I., M.Ag.",
    kapasitas: 36,
    jumlahSiswa: 35,
    ruangan: "Gedung A - R. 102",
  },
  {
    id: "cls-03",
    nama: "XI IPS 1",
    tingkat: "XI",
    waliKelasId: "gur-004",
    waliKelasNama: "Ferry Irawan, S.Pd.",
    kapasitas: 36,
    jumlahSiswa: 32,
    ruangan: "Gedung B - R. 201",
  },
  {
    id: "cls-04",
    nama: "XII MIPA 1",
    tingkat: "XII",
    waliKelasId: "gur-005",
    waliKelasNama: "Dewi Kurniasih, S.Si., M.Pd.",
    kapasitas: 36,
    jumlahSiswa: 36,
    ruangan: "Gedung C - R. 301",
  },
  {
    id: "cls-05",
    nama: "Kelas 6",
    tingkat: "6",
    waliKelasId: "gur-006",
    waliKelasNama: "Ahmad Fauzi, S.Pd.I.",
    kapasitas: 32,
    jumlahSiswa: 30,
    ruangan: "Gedung SDI - R. 601",
  },
];

export const INITIAL_MAPEL: MataPelajaran[] = [
  { id: "mpl-01", kode: "MTK", nama: "Matematika", kategori: "Wajib", kkm: 75 },
  { id: "mpl-02", kode: "BIN", nama: "Bahasa Indonesia", kategori: "Wajib", kkm: 75 },
  { id: "mpl-03", kode: "BIG", nama: "Bahasa Inggris", kategori: "Wajib", kkm: 75 },
  { id: "mpl-04", kode: "PAI", nama: "Pendidikan Agama Islam", kategori: "Wajib", kkm: 80 },
  { id: "mpl-05", kode: "FIS", nama: "Fisika", kategori: "Peminatan", kkm: 75 },
  { id: "mpl-06", kode: "BIO", nama: "Biologi", kategori: "Peminatan", kkm: 75 },
  { id: "mpl-07", kode: "KIM", nama: "Kimia", kategori: "Peminatan", kkm: 75 },
  { id: "mpl-08", kode: "EKO", nama: "Ekonomi", kategori: "Peminatan", kkm: 75 },
  { id: "mpl-09", kode: "BDH", nama: "Bahasa Daerah", kategori: "Muatan Lokal", kkm: 75 },
  { id: "mpl-10", kode: "PLBJ", nama: "Pendidikan Lingkungan & Budaya (PLBJ)", kategori: "Muatan Lokal", kkm: 75 },
  { id: "mpl-11", kode: "TFZ", nama: "Tahfidz & Tahsin Al-Qur'an", kategori: "Kecerdasan Al-Qur'an", kkm: 80 },
  { id: "mpl-12", kode: "BTQ", nama: "Baca Tulis Al-Qur'an (BTQ)", kategori: "Kecerdasan Al-Qur'an", kkm: 80 },
];

export const INITIAL_JADWAL: JadwalPelajaran[] = [
  // X MIPA 1
  { id: "jdw-01", hari: "Senin", jamMulai: "07:30", jamSelesai: "09:00", kelas: "X MIPA 1", mapel: "Pendidikan Agama Islam", guruNama: "Hj. Ratna Dewi, M.Ag.", ruangan: "R. 101" },
  { id: "jdw-02", hari: "Senin", jamMulai: "09:15", jamSelesai: "11:15", kelas: "X MIPA 1", mapel: "Matematika", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 101" },
  { id: "jdw-03", hari: "Senin", jamMulai: "11:15", jamSelesai: "12:45", kelas: "X MIPA 1", mapel: "Bahasa Inggris", guruNama: "Ferry Irawan, S.Pd.", ruangan: "R. 101" },
  { id: "jdw-04", hari: "Selasa", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 1", mapel: "Fisika", guruNama: "Drs. Eko Prasetyo, M.Pd.", ruangan: "Lab Fisika" },
  { id: "jdw-05", hari: "Selasa", jamMulai: "09:45", jamSelesai: "11:45", kelas: "X MIPA 1", mapel: "Biologi", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Biologi" },
  { id: "jdw-06", hari: "Rabu", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 1", mapel: "Bahasa Indonesia", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 101" },
  { id: "jdw-07", hari: "Kamis", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 1", mapel: "Kimia", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Kimia" },
  { id: "jdw-08", hari: "Jumat", jamMulai: "07:30", jamSelesai: "09:00", kelas: "X MIPA 1", mapel: "Pendidikan Lingkungan & Budaya (PLBJ)", guruNama: "Hj. Ratna Dewi, M.Ag.", ruangan: "R. 101" },
  { id: "jdw-09", hari: "Jumat", jamMulai: "09:15", jamSelesai: "10:45", kelas: "X MIPA 1", mapel: "Bahasa Daerah", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 101" },

  // X MIPA 2
  { id: "jdw-10", hari: "Senin", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 2", mapel: "Pendidikan Agama Islam", guruNama: "Hj. Ratna Dewi, M.Ag.", ruangan: "R. 102" },
  { id: "jdw-11", hari: "Senin", jamMulai: "09:45", jamSelesai: "11:45", kelas: "X MIPA 2", mapel: "Matematika", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 102" },
  { id: "jdw-12", hari: "Selasa", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 2", mapel: "Bahasa Indonesia", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 102" },
  { id: "jdw-13", hari: "Selasa", jamMulai: "09:45", jamSelesai: "11:45", kelas: "X MIPA 2", mapel: "Bahasa Inggris", guruNama: "Ferry Irawan, S.Pd.", ruangan: "R. 102" },
  { id: "jdw-14", hari: "Rabu", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 2", mapel: "Fisika", guruNama: "Drs. Eko Prasetyo, M.Pd.", ruangan: "Lab Fisika" },
  { id: "jdw-15", hari: "Kamis", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 2", mapel: "Kimia", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Kimia" },
  { id: "jdw-16", hari: "Jumat", jamMulai: "07:30", jamSelesai: "09:30", kelas: "X MIPA 2", mapel: "Biologi", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Biologi" },

  // XI IPS 1
  { id: "jdw-20", hari: "Senin", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XI IPS 1", mapel: "Ekonomi", guruNama: "Ferry Irawan, S.Pd.", ruangan: "R. 201" },
  { id: "jdw-21", hari: "Senin", jamMulai: "09:45", jamSelesai: "11:45", kelas: "XI IPS 1", mapel: "Bahasa Inggris", guruNama: "Ferry Irawan, S.Pd.", ruangan: "R. 201" },
  { id: "jdw-22", hari: "Selasa", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XI IPS 1", mapel: "Bahasa Indonesia", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 201" },
  { id: "jdw-23", hari: "Rabu", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XI IPS 1", mapel: "Matematika", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 201" },
  { id: "jdw-24", hari: "Kamis", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XI IPS 1", mapel: "Pendidikan Agama Islam", guruNama: "Hj. Ratna Dewi, M.Ag.", ruangan: "R. 201" },

  // XII MIPA 1
  { id: "jdw-30", hari: "Senin", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XII MIPA 1", mapel: "Fisika", guruNama: "Drs. Eko Prasetyo, M.Pd.", ruangan: "Lab Fisika" },
  { id: "jdw-31", hari: "Senin", jamMulai: "09:45", jamSelesai: "11:45", kelas: "XII MIPA 1", mapel: "Kimia", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Kimia" },
  { id: "jdw-32", hari: "Selasa", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XII MIPA 1", mapel: "Biologi", guruNama: "Dewi Kurniasih, M.Pd.", ruangan: "Lab Biologi" },
  { id: "jdw-33", hari: "Rabu", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XII MIPA 1", mapel: "Matematika", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 301" },
  { id: "jdw-34", hari: "Kamis", jamMulai: "07:30", jamSelesai: "09:30", kelas: "XII MIPA 1", mapel: "Bahasa Inggris", guruNama: "Ferry Irawan, S.Pd.", ruangan: "R. 301" },
  { id: "jdw-35", hari: "Jumat", jamMulai: "07:30", jamSelesai: "09:00", kelas: "XII MIPA 1", mapel: "Bahasa Indonesia", guruNama: "Siti Nurhaliza, M.Si.", ruangan: "R. 301" },
  { id: "jdw-36", hari: "Jumat", jamMulai: "09:15", jamSelesai: "10:45", kelas: "XII MIPA 1", mapel: "Pendidikan Agama Islam", guruNama: "Hj. Ratna Dewi, M.Ag.", ruangan: "R. 301" },

  // Kelas 6
  { id: "jdw-40", hari: "Senin", jamMulai: "07:30", jamSelesai: "09:30", kelas: "Kelas 6", mapel: "Matematika", guruNama: "Ahmad Fauzi, S.Pd.I.", ruangan: "R. 601" },
  { id: "jdw-41", hari: "Selasa", jamMulai: "07:30", jamSelesai: "09:30", kelas: "Kelas 6", mapel: "Bahasa Indonesia", guruNama: "Ahmad Fauzi, S.Pd.I.", ruangan: "R. 601" },
  { id: "jdw-42", hari: "Rabu", jamMulai: "07:30", jamSelesai: "09:30", kelas: "Kelas 6", mapel: "Pendidikan Agama Islam", guruNama: "Ahmad Fauzi, S.Pd.I.", ruangan: "R. 601" },
  { id: "jdw-43", hari: "Kamis", jamMulai: "07:30", jamSelesai: "09:30", kelas: "Kelas 6", mapel: "Tahfidz & Tahsin Al-Qur'an", guruNama: "Ahmad Fauzi, S.Pd.I.", ruangan: "Masjid" },
];

export const INITIAL_PRESENSI: PresensiRecord[] = [
  { id: "prs-01", siswaId: "sis-001", siswaNama: "Ahmad Rizky Pratama", kelas: "X MIPA 1", tanggal: "2026-09-18", status: "Hadir" },
  { id: "prs-02", siswaId: "sis-002", siswaNama: "Anisa Zahra Humaira", kelas: "X MIPA 1", tanggal: "2026-09-18", status: "Hadir" },
  { id: "prs-03", siswaId: "sis-003", siswaNama: "Bima Arya Putra", kelas: "X MIPA 1", tanggal: "2026-09-18", status: "Izin", keterangan: "Keperluan keluarga" },
  { id: "prs-04", siswaId: "sis-004", siswaNama: "Dewi Lestari Kusuma", kelas: "X MIPA 2", tanggal: "2026-09-18", status: "Hadir" },
  { id: "prs-05", siswaId: "sis-005", siswaNama: "Fajar Nugraha", kelas: "XI IPS 1", tanggal: "2026-09-18", status: "Sakit", keterangan: "Demam berdarah" },
  { id: "prs-06", siswaId: "sis-006", siswaNama: "Nabila Aulia Rahmah", kelas: "XI IPS 1", tanggal: "2026-09-18", status: "Hadir" },
  { id: "prs-07", siswaId: "sis-007", siswaNama: "Muhammad Kevin Ardiansyah", kelas: "XII MIPA 1", tanggal: "2026-09-18", status: "Hadir" },
  { id: "prs-08", siswaId: "sis-008", siswaNama: "Tiara Safitri", kelas: "XII MIPA 1", tanggal: "2026-09-18", status: "Hadir" },
  // Riwayat presensi tambahan untuk sampel rekapitulasi ketidakhadiran di cetak rapor
  { id: "prs-09", siswaId: "sis-001", siswaNama: "Ahmad Rizky Pratama", kelas: "X MIPA 1", tanggal: "2026-09-10", status: "Sakit", keterangan: "Flu dan demam ringan" },
  { id: "prs-10", siswaId: "sis-001", siswaNama: "Ahmad Rizky Pratama", kelas: "X MIPA 1", tanggal: "2026-09-11", status: "Izin", keterangan: "Acara keluarga di luar kota" },
  { id: "prs-11", siswaId: "sis-002", siswaNama: "Anisa Zahra Humaira", kelas: "X MIPA 1", tanggal: "2026-09-12", status: "Sakit", keterangan: "Sakit perut" },
  { id: "prs-12", siswaId: "sis-003", siswaNama: "Bima Arya Putra", kelas: "X MIPA 1", tanggal: "2026-09-08", status: "Alpa", keterangan: "Tanpa keterangan" },
  { id: "prs-13", siswaId: "sis-003", siswaNama: "Bima Arya Putra", kelas: "X MIPA 1", tanggal: "2026-09-09", status: "Sakit", keterangan: "Istirahat dokter" },
  { id: "prs-14", siswaId: "sis-004", siswaNama: "Dewi Lestari Kusuma", kelas: "X MIPA 2", tanggal: "2026-09-15", status: "Izin", keterangan: "Lomba olimpiade sains" },
  { id: "prs-15", siswaId: "sis-005", siswaNama: "Fajar Nugraha", kelas: "XI IPS 1", tanggal: "2026-09-17", status: "Sakit", keterangan: "Rawat inap" },
  { id: "prs-16", siswaId: "sis-006", siswaNama: "Nabila Aulia Rahmah", kelas: "XI IPS 1", tanggal: "2026-09-16", status: "Izin", keterangan: "Keperluan keluarga" },
];

export const INITIAL_NILAI: NilaiSiswa[] = [];

export const INITIAL_SPP: TagihanSPP[] = [];

export const INITIAL_JENIS_TAGIHAN: JenisTagihan[] = [
  {
    id: "jt-01",
    nama: "SPP",
    kode: "SPP",
    nominalDefault: 750000,
    keterangan: "Iuran rutin bulanan penyelenggaraan pendidikan",
    warnaBadge: "blue",
  },
  {
    id: "jt-02",
    nama: "Uang Gedung",
    kode: "GDG",
    nominalDefault: 1500000,
    keterangan: "DSP pengembangan sarana & prasarana gedung sekolah",
    warnaBadge: "indigo",
  },
  {
    id: "jt-03",
    nama: "Seragam",
    kode: "SRG",
    nominalDefault: 650000,
    keterangan: "Paket seragam batik, olahraga, jas almamater, dan atribut",
    warnaBadge: "emerald",
  },
  {
    id: "jt-04",
    nama: "Buku & Modul",
    kode: "BKU",
    nominalDefault: 450000,
    keterangan: "Buku paket tematik kurikulum merdeka & modul LKS",
    warnaBadge: "purple",
  },
  {
    id: "jt-05",
    nama: "Kegiatan & Study Tour",
    kode: "KGT",
    nominalDefault: 250000,
    keterangan: "Kunjungan edukasi, outbound, dan kegiatan kesiswaan",
    warnaBadge: "amber",
  },
  {
    id: "jt-06",
    nama: "Ujian & Asesmen",
    kode: "UJN",
    nominalDefault: 150000,
    keterangan: "Asesmen sumatif semester, ujian praktik, dan e-rapor",
    warnaBadge: "rose",
  },
  {
    id: "jt-07",
    nama: "Katering",
    kode: "KTR",
    nominalDefault: 350000,
    keterangan: "Layanan makan siang sehat dan gizi seimbang siswa",
    warnaBadge: "teal",
  },
  {
    id: "jt-08",
    nama: "Lainnya",
    kode: "LNN",
    nominalDefault: 100000,
    keterangan: "Tagihan administrasi dan iuran insidental sekolah",
    warnaBadge: "slate",
  },
];


export const INITIAL_PENGUMUMAN: Pengumuman[] = [
  {
    id: "ann-01",
    judul: "Jadwal Penilaian Tengah Semester (PTS) Ganjil TA 2025/2026",
    konten: "Pelaksanaan PTS Ganjil akan diselenggarakan mulai tanggal 28 September hingga 5 Oktober 2026. Seluruh siswa diharapkan mempersiapkan diri dan melunasi kewajiban administrasi sekolah.",
    kategori: "Ujian",
    prioritas: "Tinggi",
    tanggal: "2026-09-15",
    penulis: "Bagian Akademik & Kurikulum",
    targetRole: "Semua",
  },
  {
    id: "ann-02",
    judul: "Undangan Rapat Pleno Komite & Orang Tua / Wali Murid",
    konten: "Mengundang Bapak/Ibu Wali Murid kelas X, XI, dan XII untuk menghadiri Rapat Kerja Komite Sekolah pada hari Sabtu, 26 September 2026 pukul 08.30 WIB di Aula Utama Nusantara.",
    kategori: "Kegiatan",
    prioritas: "Sedang",
    tanggal: "2026-09-12",
    penulis: "Kepala Sekolah & Komite",
    targetRole: "Orang Tua",
  },
  {
    id: "ann-03",
    judul: "Pelatihan Implementasi Kurikulum Merdeka & E-Rapor Digital",
    konten: "Diwajibkan bagi seluruh dewan guru dan tenaga kependidikan untuk mengikuti workshop peningkatan kompetensi digital pada hari Rabu sore di Ruang Multimedia.",
    kategori: "Akademik",
    prioritas: "Normal",
    tanggal: "2026-09-10",
    penulis: "Wakasek Kurikulum",
    targetRole: "Guru",
  },
  {
    id: "ann-04",
    judul: "Penyaluran Beasiswa Prestasi & Beasiswa Tahfidz Al-Qur'an",
    konten: "Pendaftaran beasiswa prestasi akademik dan non-akademik serta hafalan Qur'an semester ganjil telah dibuka. Formulir dapat diunduh atau diambil di ruang BK.",
    kategori: "Keuangan",
    prioritas: "Sedang",
    tanggal: "2026-09-08",
    penulis: "Bagian Kesiswaan",
    targetRole: "Siswa",
  },
];

export const INITIAL_TABUNGAN: TabunganSiswa[] = [];

export const INITIAL_TRANSAKSI_TABUNGAN: TransaksiTabungan[] = [];

export const INITIAL_PESERTA_TRANSPORT: PesertaTransportasi[] = [
  {
    siswaId: "sis-001",
    isAktif: true,
    biayaBulanan: 100000,
    rute: "Rute 1 - Kebayoran & Fatmawati",
  },
  {
    siswaId: "sis-002",
    isAktif: false,
    biayaBulanan: 100000,
    rute: "-",
  },
  {
    siswaId: "sis-003",
    isAktif: true,
    biayaBulanan: 100000,
    rute: "Rute 2 - Cilandak & Ampera",
  },
  {
    siswaId: "sis-004",
    isAktif: false,
    biayaBulanan: 100000,
    rute: "-",
  },
  {
    siswaId: "sis-005",
    isAktif: true,
    biayaBulanan: 100000,
    rute: "Rute 1 - Kebayoran & Fatmawati",
  },
  {
    siswaId: "sis-006",
    isAktif: false,
    biayaBulanan: 100000,
    rute: "-",
  },
  {
    siswaId: "sis-007",
    isAktif: true,
    biayaBulanan: 100000,
    rute: "Rute 3 - Pondok Indah & Cipete",
  },
];

export function generateStudentYearRecord(
  siswa: Siswa,
  tahunAjaran: string,
  isTransport: boolean,
  biayaTransport: number = 100000,
  prePaidMonthsCount: number = 0
): RecordSPPTransportTahunAjaran {
  const bulanKeys: BulanSPP[] = [
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
  ];

  const bulanObj: any = {};
  bulanKeys.forEach((b, idx) => {
    const isLunas = idx < prePaidMonthsCount;
    const tgl = isLunas
      ? `2025-0${Math.min(idx + 7, 12)}-10`
      : undefined;

    bulanObj[b] = {
      sppStatus: isLunas ? "Lunas" : "Belum Bayar",
      sppNominal: 100000, // Rp 100.000 / bulan sesuai ketentuan
      sppTanggalBayar: tgl,
      sppMetode: isLunas ? "Transfer Bank" : undefined,
      sppNoKuitansi: isLunas
        ? `KW-SPP-${tahunAjaran.replace("/", "")}-${String(idx + 1).padStart(2, "0")}-${siswa.nisn.slice(-4)}`
        : undefined,

      isTransport,
      transportNominal: isTransport ? biayaTransport : 0,
      transportStatus: !isTransport
        ? "Tidak Menggunakan"
        : isLunas
        ? "Lunas"
        : "Belum Bayar",
      transportTanggalBayar: isTransport && isLunas ? tgl : undefined,
      transportMetode: isTransport && isLunas ? "Transfer Bank" : undefined,
      transportNoKuitansi:
        isTransport && isLunas
          ? `KW-TRN-${tahunAjaran.replace("/", "")}-${String(idx + 1).padStart(2, "0")}-${siswa.nisn.slice(-4)}`
          : undefined,
    };
  });

  return {
    id: `${siswa.id}_${tahunAjaran}`,
    siswaId: siswa.id,
    siswaNama: siswa.nama,
    nisn: siswa.nisn,
    kelas: siswa.kelas,
    tahunAjaran,
    bulan: bulanObj,
  };
}

// Generate Initial Records for 2025/2026 and 2024/2025
export const INITIAL_SPP_TRANSPORT_RECORDS: RecordSPPTransportTahunAjaran[] = [
  // 2025/2026 (Tahun Ajaran Aktif)
  ...INITIAL_SISWA.map((siswa, idx) => {
    const transportCfg = INITIAL_PESERTA_TRANSPORT.find((t) => t.siswaId === siswa.id);
    const isTransport = transportCfg?.isAktif ?? (idx % 2 === 0);
    const paidCount = idx === 0 ? 3 : idx === 1 ? 2 : idx === 2 ? 1 : idx === 3 ? 4 : idx === 4 ? 0 : 2;
    return generateStudentYearRecord(siswa, "2025/2026", isTransport, 100000, paidCount);
  }),
  // 2024/2025 (Tahun Lalu - 100% Lunas)
  ...INITIAL_SISWA.map((siswa, idx) => {
    const transportCfg = INITIAL_PESERTA_TRANSPORT.find((t) => t.siswaId === siswa.id);
    const isTransport = transportCfg?.isAktif ?? (idx % 2 === 0);
    return generateStudentYearRecord(siswa, "2024/2025", isTransport, 100000, 12);
  }),
  // 2026/2027 (Tahun Depan - 0% Lunas)
  ...INITIAL_SISWA.map((siswa, idx) => {
    const transportCfg = INITIAL_PESERTA_TRANSPORT.find((t) => t.siswaId === siswa.id);
    const isTransport = transportCfg?.isAktif ?? (idx % 2 === 0);
    return generateStudentYearRecord(siswa, "2026/2027", isTransport, 100000, 0);
  }),
];

export const INITIAL_TRANSAKSI_SPP_TRANSPORT: TransaksiSPPTransport[] = [
  {
    id: "trx-spp-01",
    noKuitansi: "KW-SPP-20252026-001",
    siswaId: "sis-001",
    siswaNama: "Ahmad Rizky Pratama",
    nisn: "0078129034",
    kelas: "X MIPA 1",
    tahunAjaran: "2025/2026",
    jenis: "Paket Keduanya",
    bulan: ["Juli", "Agustus", "September"],
    totalNominal: 600000, // 3x SPP (300k) + 3x Transport (300k)
    metodePembayaran: "Transfer Bank",
    tanggalBayar: "2025-07-10",
    petugas: "Dr. H. Muhammad Rasyid, M.Pd.",
    keterangan: "Pembayaran SPP dan Transportasi 3 bulan (Triwulan 1)",
  },
  {
    id: "trx-spp-02",
    noKuitansi: "KW-SPP-20252026-002",
    siswaId: "sis-002",
    siswaNama: "Anisa Zahra Humaira",
    nisn: "0078129035",
    kelas: "X MIPA 1",
    tahunAjaran: "2025/2026",
    jenis: "SPP",
    bulan: ["Juli", "Agustus"],
    totalNominal: 200000,
    metodePembayaran: "Potong Tabungan Siswa",
    tanggalBayar: "2025-08-05",
    petugas: "Siti Nurhaliza, M.Si.",
    keterangan: "Pembayaran SPP Juli-Agustus via autodebet tabungan",
  },
  {
    id: "trx-spp-03",
    noKuitansi: "KW-SPP-20252026-003",
    siswaId: "sis-003",
    siswaNama: "Bima Arya Putra",
    nisn: "0078129036",
    kelas: "X MIPA 1",
    tahunAjaran: "2025/2026",
    jenis: "Paket Keduanya",
    bulan: ["Juli"],
    totalNominal: 200000,
    metodePembayaran: "Tunai",
    tanggalBayar: "2025-07-15",
    petugas: "Dr. H. Muhammad Rasyid, M.Pd.",
    keterangan: "Pembayaran tunai SPP & jemputan bulan Juli",
  },
];

// ===================================================
// LMS (Learning Management System) Initial Mock Data
// ===================================================

export const INITIAL_LMS_MATERI: LMSMateri[] = [
  {
    id: "mat-01",
    judul: "Persamaan dan Pertidaksamaan Nilai Mutlak Linear",
    mapel: "Matematika Wajib",
    kelas: "X MIPA 1",
    guruNama: "Siti Nurhaliza, S.Pd., M.Si.",
    guruId: "usr-guru",
    pertemuanKe: 1,
    durasiMenit: 45,
    tipeKonten: "video",
    urlKonten: "https://www.youtube.com/embed/jfKfPfyJRdk",
    fileLampiran: "Modul-01-Nilai-Mutlak-Matematika-X.pdf",
    deskripsi:
      "Membahas konsep dasar definisi nilai mutlak, sifat-sifat persamaan linear satu variabel yang memuat nilai mutlak, dan contoh penyelesaian soal kontekstual.",
    createdAt: "2025-08-01",
    sudahDibacaSiswaIds: ["sis-001", "sis-002"],
  },
  {
    id: "mat-02",
    judul: "Hukum Newton tentang Gerak dan Aplikasinya",
    mapel: "Fisika",
    kelas: "X MIPA 1",
    guruNama: "Dewi Kurniasih, S.Si., M.Pd.",
    guruId: "usr-guru-dewi",
    pertemuanKe: 2,
    durasiMenit: 60,
    tipeKonten: "pdf",
    urlKonten: "https://example.com/ebook-fisika-hukum-newton.pdf",
    fileLampiran: "Lembar-Kerja-Eksperimen-Gaya-Gesek.pdf",
    deskripsi:
      "Kajian mendalam tentang Hukum I, II, dan III Newton. Dilengkapi dengan diagram gaya bebas, gaya normal, gaya gesek statis/kinetis, dan aplikasi pada bidang miring.",
    createdAt: "2025-08-03",
    sudahDibacaSiswaIds: ["sis-001"],
  },
  {
    id: "mat-03",
    judul: "Struktur dan Fungsi Organel Sel Eukariotik & Prokariotik",
    mapel: "Biologi",
    kelas: "X MIPA 1",
    guruNama: "Hj. Ratna Dewi, S.Pd.I., M.Ag.",
    guruId: "usr-guru-ratna",
    pertemuanKe: 1,
    durasiMenit: 40,
    tipeKonten: "artikel",
    fileLampiran: "Atlas-Organel-Sel-Biologi.pdf",
    deskripsi:
      "Perbedaan mendasar antara sel hewan dan tumbuhan, membran sel, mitokondria, nukleus, kloroplas, serta proses transport pasif dan aktif melalui membran.",
    createdAt: "2025-08-05",
    sudahDibacaSiswaIds: ["sis-001", "sis-003"],
  },
  {
    id: "mat-04",
    judul: "Struktur dan Kaidah Kebahasaan Teks Laporan Hasil Observasi",
    mapel: "Bahasa Indonesia",
    kelas: "X MIPA 1",
    guruNama: "Ferry Irawan, S.Pd.",
    guruId: "usr-guru-ferry",
    pertemuanKe: 2,
    durasiMenit: 35,
    tipeKonten: "link",
    urlKonten: "https://badanbahasa.kemdikbud.go.id",
    fileLampiran: "Panduan-Menulis-LHO-Standar-Kurikulum.pdf",
    deskripsi:
      "Pedoman menyusun teks observasi objektif berbasis fakta, penggunaan frasa nomina, verba relasional, dan penyusunan kalimat definisi serta deskripsi.",
    createdAt: "2025-08-07",
    sudahDibacaSiswaIds: ["sis-002"],
  },
  {
    id: "mat-k6-01",
    judul: "Operasi Hitung Campuran Bilangan Bulat & Pecahan",
    mapel: "Matematika",
    kelas: "Kelas 6",
    guruNama: "Ahmad Fauzi, S.Pd.I.",
    guruId: "usr-guru-kelas6",
    pertemuanKe: 1,
    durasiMenit: 35,
    tipeKonten: "video",
    urlKonten: "https://www.youtube.com/embed/jfKfPfyJRdk",
    fileLampiran: "Modul-Matematika-Operasi-Campuran-Kelas6.pdf",
    deskripsi: "Pendalaman konsep urutan operasi hitung campuran (KABATAKU), sifat distributif, dan aplikasi soal cerita kontekstual kelas 6.",
    createdAt: "2025-08-01",
    sudahDibacaSiswaIds: [],
  },
  {
    id: "mat-k6-02",
    judul: "Tematik: Selamatkan Makhluk Hidup - Perkembangbiakan Tumbuhan dan Hewan",
    mapel: "Tematik",
    kelas: "Kelas 6",
    guruNama: "Ahmad Fauzi, S.Pd.I.",
    guruId: "usr-guru-kelas6",
    pertemuanKe: 2,
    durasiMenit: 40,
    tipeKonten: "artikel",
    fileLampiran: "Rangkuman-Tema1-Kelas6.pdf",
    deskripsi: "Karakteristik organ reproduksi bunga, penyerbukan bastar dan silang, serta ragam perkembangbiakan vegetatif alami dan buatan.",
    createdAt: "2025-08-03",
    sudahDibacaSiswaIds: [],
  },
];

export const INITIAL_LMS_TUGAS: LMSTugas[] = [
  {
    id: "tgs-01",
    judul: "Tugas 1: Analisis Persamaan Nilai Mutlak Soal Cerita",
    mapel: "Matematika Wajib",
    kelas: "X MIPA 1",
    guruNama: "Siti Nurhaliza, S.Pd., M.Si.",
    guruId: "usr-guru",
    deadline: "2025-09-25T23:59",
    bobotPoin: 100,
    filePetunjuk: "Soal-Latihan-Nilai-Mutlak-Bab1.pdf",
    deskripsi:
      "Kerjakan 5 butir soal pemodelan matematika terkait toleransi berat kemasan produk pada modul halaman 14. Tuliskan langkah pengerjaan terstruktur, foto/scan dalam format PDF, lalu unggah sebelum tenggat waktu.",
    createdAt: "2025-08-10",
  },
  {
    id: "tgs-02",
    judul: "Laporan Praktikum Mandiri: Koefisien Gesek Bidang Miring",
    mapel: "Fisika",
    kelas: "X MIPA 1",
    guruNama: "Dewi Kurniasih, S.Si., M.Pd.",
    guruId: "usr-guru-dewi",
    deadline: "2025-09-28T23:59",
    bobotPoin: 100,
    filePetunjuk: "Format-Laporan-Praktikum-Fisika.docx",
    deskripsi:
      "Gunakan buku/papan dan balok kecil di rumah untuk mengukur sudut kemiringan saat benda mulai meluncur. Hitung nilai tan(θ) sebagai koefisien gesek statis. Lampirkan foto alat dan data perhitungan.",
    createdAt: "2025-08-12",
  },
  {
    id: "tgs-03",
    judul: "Karya Tulis Observasi: Keanekaragaman Flora Lingkungan Sekolah",
    mapel: "Bahasa Indonesia",
    kelas: "X MIPA 1",
    guruNama: "Ferry Irawan, S.Pd.",
    guruId: "usr-guru-ferry",
    deadline: "2025-10-05T17:00",
    bobotPoin: 100,
    filePetunjuk: "Rubrik-Penilaian-LHO.pdf",
    deskripsi:
      "Buatlah esai teks laporan hasil observasi minimal 500 kata dengan tema pepohonan peneduh atau taman apotek hidup di lingkungan sekolah. Perhatikan kaidah konjungsi dan tanda baca baku PUEBI.",
    createdAt: "2025-08-15",
  },
  {
    id: "tgs-k6-01",
    judul: "Tugas Tematik: Membuat Bagan Daur Hidup & Pelestarian Hewan Langka",
    mapel: "Tematik",
    kelas: "Kelas 6",
    guruNama: "Ahmad Fauzi, S.Pd.I.",
    guruId: "usr-guru-kelas6",
    deadline: "2025-09-30T23:59",
    bobotPoin: 100,
    filePetunjuk: "Petunjuk-Tugas-Tema1-Kelas6.pdf",
    deskripsi: "Pilihlah salah satu hewan langka khas Indonesia (misal: Komodo, Badak Bercula Satu, atau Cendrawasih). Buatlah bagan daur hidup dan upaya pelestariannya.",
    createdAt: "2025-08-10",
  },
];

export const INITIAL_LMS_SUBMISSIONS: LMSSubmission[] = [
  {
    id: "sub-01",
    tugasId: "tgs-01",
    siswaId: "sis-001",
    siswaNama: "Ahmad Rizky Pratama",
    siswaNisn: "0078129034",
    kelas: "X MIPA 1",
    tanggalKumpul: "2025-08-14 14:30",
    catatanSiswa:
      "Tugas mandiri nomor 1 sampai 5 telah dikerjakan lengkap dengan grafik himpunan penyelesaiannya. Terima kasih Bu Siti.",
    fileJawabanUrl: "https://drive.google.com/file/d/ahmad-rizky-tugas-matematika-01.pdf",
    status: "Dinilai",
    nilai: 92,
    feedbackGuru:
      "Luar biasa Rizky! Penjabaran sifat nilai mutlak nomor 4 sangat rapi dan pembagian kasus positif/negatif sangat tepat.",
    dinilaiPada: "2025-08-15 09:15",
  },
  {
    id: "sub-02",
    tugasId: "tgs-01",
    siswaId: "sis-002",
    siswaNama: "Anisa Zahra Humaira",
    siswaNisn: "0078129035",
    kelas: "X MIPA 1",
    tanggalKumpul: "2025-08-15 10:12",
    catatanSiswa: "Sudah diupload Bu, mohon dikoreksi jika ada salah pada langkah nomor 3.",
    fileJawabanUrl: "https://drive.google.com/file/d/anisa-tugas-matematika-01.pdf",
    status: "Dinilai",
    nilai: 88,
    feedbackGuru: "Sudah bagus, perhatikan kembali kesimpulan akhir pada interval x < 0.",
    dinilaiPada: "2025-08-16 11:20",
  },
  {
    id: "sub-03",
    tugasId: "tgs-02",
    siswaId: "sis-001",
    siswaNama: "Ahmad Rizky Pratama",
    siswaNisn: "0078129034",
    kelas: "X MIPA 1",
    tanggalKumpul: "2025-08-16 19:40",
    catatanSiswa: "Pengambilan data dilakukan 5 kali percobaan sudut elevasi untuk menghitung rata-rata μs.",
    fileJawabanUrl: "https://drive.google.com/file/d/rizky-laporan-fisika-gesek.pdf",
    status: "Diserahkan",
  },
];

export const INITIAL_LMS_KUIS: LMSKuis[] = [
  {
    id: "quiz-01",
    judul: "Kuis Harian 1: Konsep Nilai Mutlak & Sistem Persamaan",
    mapel: "Matematika Wajib",
    kelas: "X MIPA 1",
    guruNama: "Siti Nurhaliza, S.Pd., M.Si.",
    durasiMenit: 15,
    kkm: 75,
    deadline: "2025-09-30T23:59",
    deskripsi:
      "Uji pemahaman komprehensif Bab I. Terdiri atas 4 butir soal pilihan ganda berbobot sama (25 poin per soal). Waktu pengerjaan 15 menit.",
    createdAt: "2025-08-12",
    soalList: [
      {
        id: "soal-01-1",
        pertanyaan: "Himpunan penyelesaian dari persamaan |2x - 3| = 7 adalah...",
        pilihan: ["{-2, 5}", "{-5, 2}", "{2, 5}", "{-2, -5}", "{5}"],
        kunciJawaban: 0, // A: {-2, 5}
        pembahasan:
          "Kasus 1: 2x - 3 = 7 => 2x = 10 => x = 5. Kasus 2: 2x - 3 = -7 => 2x = -4 => x = -2. Maka HP = {-2, 5}.",
        poin: 25,
      },
      {
        id: "soal-01-2",
        pertanyaan: "Nilai x yang memenuhi persamaan |x + 5| = |3x - 1| adalah...",
        pilihan: ["x = 3 atau x = -1", "x = -3 atau x = 1", "x = 3 atau x = 1", "x = 2 atau x = -3", "x = 5"],
        kunciJawaban: 0, // A
        pembahasan:
          "Kuadratkan kedua ruas: (x + 5)^2 - (3x - 1)^2 = 0 => (4x + 4)(-2x + 6) = 0 => x = -1 atau x = 3.",
        poin: 25,
      },
      {
        id: "soal-01-3",
        pertanyaan: "Suhu normal tubuh manusia adalah 37°C dengan toleransi fluktuasi sebesar 0,5°C. Model persamaan nilai mutlak yang tepat untuk suhu T adalah...",
        pilihan: [
          "|T - 37| = 0,5",
          "|T + 37| = 0,5",
          "|T - 0,5| = 37",
          "|T + 0,5| = 37",
          "|37 - 0,5| = T",
        ],
        kunciJawaban: 0, // A
        pembahasan:
          "Penyimpangan suhu T dari nilai acuan 37°C sebesar maksimum 0,5°C dimodelkan sebagai |T - 37| = 0,5.",
        poin: 25,
      },
      {
        id: "soal-01-4",
        pertanyaan: "Penyelesaian dari |x - 2| = -4 adalah...",
        pilihan: [
          "Himpunan Kosong (tidak ada solusi nyata)",
          "x = 6",
          "x = -2",
          "x = 2 atau x = -6",
          "x = 0",
        ],
        kunciJawaban: 0, // A
        pembahasan:
          "Berdasarkan definisi nilai mutlak, |a| selalu bernilai non-negatif (|a| >= 0). Nilai mutlak tidak pernah menghasilkan bilangan negatif (-4), sehingga tidak ada nilai x yang memenuhi.",
        poin: 25,
      },
    ],
  },
  {
    id: "quiz-02",
    judul: "Kuis Mini 2: Hukum II Newton & Gaya Gesek",
    mapel: "Fisika",
    kelas: "X MIPA 1",
    guruNama: "Dewi Kurniasih, S.Si., M.Pd.",
    durasiMenit: 10,
    kkm: 75,
    deadline: "2025-10-02T23:59",
    deskripsi:
      "Kuis pengayaan pemahaman percepatan benda dan gaya gesekan. 3 butir soal konsep & numerik sederhana.",
    createdAt: "2025-08-14",
    soalList: [
      {
        id: "soal-02-1",
        pertanyaan: "Sebuah balok bermassa 4 kg ditarik gaya horizontal sebesar 20 N pada lantai licin (tanpa gesekan). Percepatan yang dialami balok adalah...",
        pilihan: ["5 m/s²", "4 m/s²", "2 m/s²", "8 m/s²", "10 m/s²"],
        kunciJawaban: 0, // 5 m/s²
        pembahasan: "Menggunakan Hukum II Newton: ΣF = m * a => 20 N = 4 kg * a => a = 5 m/s².",
        poin: 35,
      },
      {
        id: "soal-02-2",
        pertanyaan: "Arah gaya gesekan yang dialami oleh benda yang bergerak di atas permukaan selalu...",
        pilihan: [
          "Berlawanan dengan kecenderungan arah gerak benda",
          "Searah dengan gaya dorong",
          "Tegak lurus terhadap bidang kontak",
          "Searah dengan gaya gravitasi bumi",
          "Selalu searah jarum jam",
        ],
        kunciJawaban: 0,
        pembahasan: "Gaya gesek selalu bekerja sejajar bidang kontak dan berlawanan arah dengan gerak relatif benda.",
        poin: 35,
      },
      {
        id: "soal-02-3",
        pertanyaan: "Jika resultan gaya yang bekerja pada suatu benda adalah nol (ΣF = 0), maka benda tersebut...",
        pilihan: [
          "Diam atau bergerak lurus dengan kecepatan konstan (GLB)",
          "Pasti dalam keadaan diam mutlak",
          "Pasti mengalami percepatan konstan",
          "Kecepatannya semakin bertambah seiring waktu",
          "Akan berputar mengitari porosnya",
        ],
        kunciJawaban: 0,
        pembahasan: "Hukum I Newton (Kelembaman): Jika ΣF = 0, benda diam tetap diam, atau benda bergerak tetap bergerak lurus beraturan (GLB).",
        poin: 30,
      },
    ],
  },
  {
    id: "quiz-k6-01",
    judul: "Simulasi CBT Ujian Sekolah: Matematika & IPA Kelas 6",
    mapel: "Matematika",
    kelas: "Kelas 6",
    guruNama: "Ahmad Fauzi, S.Pd.I.",
    durasiMenit: 30,
    kkm: 75,
    deadline: "2025-10-15T23:59",
    deskripsi: "Latihan simulasi CBT penilaian harian terpadu untuk siswa Kelas 6 SDI.",
    createdAt: "2025-08-20",
    soalList: [
      {
        id: "soal-k6-1",
        pertanyaan: "Hasil dari 2 1/2 + 1.25 - 3/4 adalah...",
        pilihan: ["2.5", "3.0", "3.25", "3.5", "4.0"],
        kunciJawaban: 1,
        pembahasan: "2 1/2 = 2.5. Maka 2.5 + 1.25 - 0.75 = 3.75 - 0.75 = 3.0.",
        poin: 50,
      },
      {
        id: "soal-k6-2",
        pertanyaan: "Tumbuhan berikut yang berkembang biak secara alami melalui tunas adventif daun adalah...",
        pilihan: ["Pisang", "Bambu", "Cocor Bebek", "Kunyit", "Kentang"],
        kunciJawaban: 2,
        pembahasan: "Cocor bebek membentuk tunas adventif pada tepi lekukan daunnya.",
        poin: 50,
      },
    ],
  },
];

export const INITIAL_LMS_ATTEMPTS: LMSKuisAttempt[] = [
  {
    id: "att-01",
    kuisId: "quiz-01",
    siswaId: "sis-001",
    siswaNama: "Ahmad Rizky Pratama",
    siswaNisn: "0078129034",
    kelas: "X MIPA 1",
    jawaban: {
      "soal-01-1": 0,
      "soal-01-2": 0,
      "soal-01-3": 0,
      "soal-01-4": 0,
    },
    skor: 100,
    totalBenar: 4,
    totalSoal: 4,
    statusLulus: true,
    selesaiPada: "2025-08-16 14:10",
  },
  {
    id: "att-02",
    kuisId: "quiz-01",
    siswaId: "sis-002",
    siswaNama: "Anisa Zahra Humaira",
    siswaNisn: "0078129035",
    kelas: "X MIPA 1",
    jawaban: {
      "soal-01-1": 0,
      "soal-01-2": 1, // Salah
      "soal-01-3": 0,
      "soal-01-4": 0,
    },
    skor: 75,
    totalBenar: 3,
    totalSoal: 4,
    statusLulus: true,
    selesaiPada: "2025-08-16 15:05",
  },
];

export const INITIAL_LMS_FORUM: LMSForumDiskusi[] = [
  {
    id: "frm-01",
    judul: "Diskusi Pemodelan Persamaan Nilai Mutlak pada Arus Listrik AC",
    mapel: "Matematika Wajib",
    kelas: "X MIPA 1",
    pembuatNama: "Ahmad Rizky Pratama",
    pembuatRole: "siswa",
    pembuatAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150",
    isi: "Izin bertanya Bu Siti dan teman-teman, apakah konsep nilai mutlak juga bisa diaplikasikan untuk menghitung tegangan efektif pada gelombang sinus bolak-balik (AC)? Terima kasih.",
    tanggal: "2025-08-14 16:20",
    komentarList: [
      {
        id: "kom-01-1",
        penulisNama: "Siti Nurhaliza, S.Pd., M.Si.",
        penulisRole: "guru",
        penulisAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
        isi: "Pertanyaan yang sangat cerdas, Rizky! Tepat sekali, nilai mutlak digunakan pada rectifier (penyearah gelombang penuh) di mana sinyal tegangan negatif dibalik menjadi positif |V(t)| sebelum dihaluskan kapasitor. Kita akan bahas ini saat korelasi dengan materi Fisika Listrik ya.",
        tanggal: "2025-08-14 17:05",
      },
      {
        id: "kom-01-2",
        penulisNama: "Anisa Zahra Humaira",
        penulisRole: "siswa",
        penulisAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
        isi: "Wah menarik sekali! Terima kasih Bu penjelasannya jadi lebih paham penerapan praktisnya di dunia elektronika.",
        tanggal: "2025-08-14 17:30",
      },
    ],
  },
  {
    id: "frm-02",
    judul: "Tips Membedakan Gaya Gesek Statis dan Kinetis pada Bidang Miring",
    mapel: "Fisika",
    kelas: "X MIPA 1",
    pembuatNama: "Dewi Kurniasih, S.Si., M.Pd.",
    pembuatRole: "guru",
    pembuatAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    isi: "Halo anak-anak X MIPA 1! Ingat trik cepatnya: bandingkan dulu komponen gaya penggerak (W sin θ) dengan gaya gesek statis maksimum (fs_max = μs * W cos θ). Jika W sin θ <= fs_max, benda masih diam dan gaya gesek yang bekerja sama dengan W sin θ (bukan fs_max). Silakan ajukan pertanyaan di bawah ini jika masih ragu!",
    tanggal: "2025-08-15 08:30",
    komentarList: [
      {
        id: "kom-02-1",
        penulisNama: "Bima Arya Putra",
        penulisRole: "siswa",
        penulisAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
        isi: "Izin bertanya Bu Dewi, kalau bendanya diberi dorongan awal sedikit apakah langsung berubah menjadi gesekan kinetis?",
        tanggal: "2025-08-15 09:10",
      },
      {
        id: "kom-02-2",
        penulisNama: "Dewi Kurniasih, S.Si., M.Pd.",
        penulisRole: "guru",
        penulisAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
        isi: "Benar Bima! Begitu benda bergerak meluncur, permukaan antar molekul terlepas sehingga yang berlaku seketika adalah gaya gesek kinetis (fk = μk * N), di mana nilainya biasanya lebih kecil daripada fs_max.",
        tanggal: "2025-08-15 09:45",
      },
    ],
  },
];

export const INITIAL_LMS_MEETINGS: LMSVirtualMeeting[] = [
  {
    id: "meet-01",
    judul: "KBM Daring Matematika: Pendalaman Nilai Mutlak Kuadrat",
    mapel: "Matematika Wajib",
    kelas: "X MIPA 1",
    guruNama: "Siti Nurhaliza, S.Pd., M.Si.",
    platform: "Google Meet",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    tanggal: "2025-09-22",
    jamMulai: "08:00",
    jamSelesai: "09:30",
    status: "Akan Datang",
    keterangan: "Siapkan buku catatan dan modul halaman 12. Sesi interaktif tanya jawab soal latihan.",
  },
  {
    id: "meet-02",
    judul: "Tutorial Lab Virtual Fisika: Simulasi PhET Gaya dan Gerak",
    mapel: "Fisika",
    kelas: "X MIPA 1",
    guruNama: "Dewi Kurniasih, S.Si., M.Pd.",
    platform: "Zoom",
    meetingUrl: "https://zoom.us/j/1234567890",
    tanggal: "2025-09-24",
    jamMulai: "10:00",
    jamSelesai: "11:30",
    status: "Akan Datang",
    keterangan: "Praktikum daring interaktif menggunakan software simulasi PhET Colorado.",
  },
];

export const INITIAL_LMS_BANK_SOAL: LMSBankSoal[] = [
  {
    id: "pkt-bs-01",
    kode: "PKT-MAT-01",
    judul: "Bank Soal Matematika: Persamaan Nilai Mutlak & Matriks",
    deskripsi: "Paket butir soal terstandar mengenai persamaan nilai mutlak, akar persamaan kuadrat, dan aljabar matriks.",
    mapel: "Matematika Wajib",
    tingkatKelas: "X",
    topik: "Nilai Mutlak, Persamaan Kuadrat & Matriks",
    pembuatGuru: "Siti Nurhaliza, S.Pd., M.Si.",
    createdAt: "2025-08-01",
    soalList: [
      {
        id: "bs-01",
        kode: "BS-MAT-01",
        tingkatKesulitan: "Mudah",
        pertanyaan: "Himpunan penyelesaian dari persamaan nilai mutlak |2x - 5| = 7 adalah...",
        pilihan: ["{-1, 6}", "{-6, 1}", "{-1, -6}", "{1, 6}", "{-2, 5}"],
        kunciJawaban: 0,
        pembahasan: "Persamaan |2x - 5| = 7 memiliki dua kemungkinan:\n1) 2x - 5 = 7 => 2x = 12 => x = 6\n2) 2x - 5 = -7 => 2x = -2 => x = -1.\nJadi, himpunan penyelesaiannya adalah {-1, 6}.",
        poinDefault: 10,
      },
      {
        id: "bs-02",
        kode: "BS-MAT-02",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Jika x₁ dan x₂ adalah akar-akar persamaan kuadrat 2x² - 6x + 4 = 0, maka nilai dari (x₁ + x₂)² - 2x₁x₂ adalah...",
        pilihan: ["5", "7", "9", "11", "13"],
        kunciJawaban: 0,
        pembahasan: "Berdasarkan teorema Vieta: x₁ + x₂ = -(-6)/2 = 3 dan x₁x₂ = 4/2 = 2.\nMaka: (x₁ + x₂)² - 2x₁x₂ = (3)² - 2(2) = 9 - 4 = 5.",
        poinDefault: 15,
      },
      {
        id: "bs-03",
        kode: "BS-MAT-03",
        tingkatKesulitan: "Sukar",
        pertanyaan: "Diketahui matriks A = [[2, 3], [1, 4]]. Determinan dari invers matriks A (det(A⁻¹)) adalah...",
        pilihan: ["5", "1/5", "-5", "-1/5", "1/10"],
        kunciJawaban: 1,
        pembahasan: "Determinan matriks A: det(A) = (2)(4) - (3)(1) = 8 - 3 = 5.\nBerdasarkan sifat matriks: det(A⁻¹) = 1 / det(A) = 1/5.",
        poinDefault: 20,
      },
    ],
  },
  {
    id: "pkt-bs-02",
    kode: "PKT-FIS-01",
    judul: "Bank Soal Fisika: Dinamika Gerak Newton & Energi Mekanik",
    deskripsi: "Latihan butir soal terstandar Hukum II Newton, GLBB, dan hukum kekekalan energi mekanik.",
    mapel: "Fisika",
    tingkatKelas: "X",
    topik: "Hukum Newton, GLBB & Energi Mekanik",
    pembuatGuru: "Dewi Kurniasih, S.Si., M.Pd.",
    createdAt: "2025-08-02",
    soalList: [
      {
        id: "bs-04",
        kode: "BS-FIS-01",
        tingkatKesulitan: "Mudah",
        pertanyaan: "Sebuah balok bermassa 4 kg ditarik dengan gaya mendatar F = 20 N pada permukaan lantai licin tanpa gesekan. Percepatan gerak balok tersebut adalah...",
        pilihan: ["2 m/s²", "4 m/s²", "5 m/s²", "8 m/s²", "10 m/s²"],
        kunciJawaban: 2,
        pembahasan: "Berdasarkan Hukum II Newton: ΣF = m · a => a = F / m = 20 N / 4 kg = 5 m/s².",
        poinDefault: 10,
      },
      {
        id: "bs-05",
        kode: "BS-FIS-02",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Sebuah mobil bergerak dengan kecepatan awal 10 m/s dan mengalami percepatan konstan 2 m/s² selama 5 detik. Jarak yang ditempuh mobil selama selang waktu tersebut adalah...",
        pilihan: ["50 meter", "60 meter", "75 meter", "85 meter", "100 meter"],
        kunciJawaban: 2,
        pembahasan: "Rumus jarak GLBB: s = v₀·t + ½·a·t² = 10(5) + ½(2)(5)² = 50 + 25 = 75 meter.",
        poinDefault: 15,
      },
      {
        id: "bs-06",
        kode: "BS-FIS-03",
        tingkatKesulitan: "Sukar",
        pertanyaan: "Sebuah bola bermassa 0.5 kg dilemparkan vertikal ke atas dari permukaan tanah dengan kecepatan awal 20 m/s (g = 10 m/s²). Energi kinetik bola pada saat mencapai ketinggian 15 meter dari tanah adalah...",
        pilihan: ["25 Joule", "50 Joule", "75 Joule", "100 Joule", "150 Joule"],
        kunciJawaban: 0,
        pembahasan: "Energi mekanik awal (di tanah): EM₁ = EK₁ = ½ m v₀² = ½ (0.5)(20)² = 100 Joule.\nPada ketinggian h = 15 m: EP₂ = m·g·h = 0.5 × 10 × 15 = 75 Joule.\nKekekalan energi mekanik: EM₁ = EM₂ => 100 = EK₂ + 75 => EK₂ = 25 Joule.",
        poinDefault: 20,
      },
    ],
  },
  {
    id: "pkt-bs-03",
    kode: "PKT-BIO-01",
    judul: "Bank Soal Biologi: Sitologi Seluler & Genetika Pewarisan Sifat",
    deskripsi: "Paket soal fungsi organel sel eukariotik, peranan nukleus, serta persilangan monohibrid intermedier.",
    mapel: "Biologi",
    tingkatKelas: "XII",
    topik: "Struktur Sel & Hukum Pewarisan Sifat",
    pembuatGuru: "Hj. Ratna Dewi, S.Pd.I., M.Ag.",
    createdAt: "2025-08-03",
    soalList: [
      {
        id: "bs-07",
        kode: "BS-BIO-01",
        tingkatKesulitan: "Mudah",
        pertanyaan: "Organel sel yang berperan sebagai pusat pengendali seluruh aktivitas kehidupan dan pembawa materi genetik sel adalah...",
        pilihan: ["Ribosom", "Nukleus", "Mitokondria", "Retikulum Endoplasma", "Vakuola"],
        kunciJawaban: 1,
        pembahasan: "Nukleus (inti sel) memuat DNA dan kromosom yang mengontrol aktivitas sintesis protein dan regulasi seluler.",
        poinDefault: 10,
      },
      {
        id: "bs-08",
        kode: "BS-BIO-02",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Persilangan antara tanaman berbunga merah (MM) dengan tanaman berbunga putih (mm) menghasilkan keturunan F1 semuanya merah muda (Mm). Jika F1 disilangkan sesamanya, perbandingan fenotipe pada F2 adalah...",
        pilihan: ["3 Merah : 1 Putih", "1 Merah : 2 Merah Muda : 1 Putih", "9 Merah : 3 Merah Muda : 3 Putih : 1 Kuning", "2 Merah : 2 Putih", "Semua Merah Muda"],
        kunciJawaban: 1,
        pembahasan: "Ini merupakan contoh dominansi tidak penuh (intermedier). Genotipe F2: 1 MM (Merah) : 2 Mm (Merah Muda) : 1 mm (Putih).",
        poinDefault: 15,
      },
    ],
  },
  {
    id: "pkt-bs-04",
    kode: "PKT-KIM-01",
    judul: "Bank Soal Kimia: Struktur Atom & Konfigurasi Aufbau",
    deskripsi: "Kumpulan butir soal pemahaman konfigurasi elektron menurut prinsip Aufbau dan diagram orbital klorin.",
    mapel: "Kimia",
    tingkatKelas: "X",
    topik: "Struktur Atom & Konfigurasi Elektron",
    pembuatGuru: "Dewi Kurniasih, S.Si., M.Pd.",
    createdAt: "2025-08-05",
    soalList: [
      {
        id: "bs-09",
        kode: "BS-KIM-01",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Unsur Klorin memiliki nomor atom 17. Konfigurasi elektron atom klorin pada keadaan dasar menurut prinsip Aufbau adalah...",
        pilihan: [
          "1s² 2s² 2p⁶ 3s² 3p⁵",
          "1s² 2s² 2p⁶ 3s¹ 3p⁶",
          "1s² 2s² 2p⁵ 3s² 3p⁶",
          "1s² 2s² 2p⁶ 3s² 3p⁴ 4s¹",
          "1s² 2s² 2p⁶ 3d⁷"
        ],
        kunciJawaban: 0,
        pembahasan: "Nomor atom 17 memiliki 17 elektron. Urutan pengisian orbital energi: 1s² (2) -> 2s² (4) -> 2p⁶ (10) -> 3s² (12) -> 3p⁵ (17).",
        poinDefault: 15,
      },
    ],
  },
  {
    id: "pkt-bs-05",
    kode: "PKT-IND-01",
    judul: "Bank Soal Bahasa Indonesia: Struktur Teks LHO & Eksplanasi",
    deskripsi: "Analisis struktur definisi umum laporan hasil observasi dan konjungsi kausalitas teks eksplanasi ilmiah.",
    mapel: "Bahasa Indonesia",
    tingkatKelas: "X",
    topik: "Teks LHO & Teks Eksplanasi",
    pembuatGuru: "Ahmad Fauzi, S.Pd.",
    createdAt: "2025-08-06",
    soalList: [
      {
        id: "bs-10",
        kode: "BS-IND-01",
        tingkatKesulitan: "Mudah",
        pertanyaan: "Struktur pembangun teks Laporan Hasil Observasi (LHO) yang memuat pembuka, pengantar, atau keterangan umum mengenai objek yang diamati dinamakan...",
        pilihan: [
          "Deskripsi Bagian",
          "Pernyataan Umum (Definisi Umum)",
          "Deskripsi Manfaat",
          "Orientasi Alur",
          "Reorientasi Simpulan"
        ],
        kunciJawaban: 1,
        pembahasan: "Pernyataan Umum atau Definisi Umum berisi keterangan ringkas mengenai klasifikasi dan identifikasi awal dari objek yang diobservasi.",
        poinDefault: 10,
      },
      {
        id: "bs-11",
        kode: "BS-IND-02",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Konjungsi kausalitas yang tepat untuk menghubungkan sebab-akibat fenomena alam dalam teks eksplanasi adalah...",
        pilihan: [
          "sementara itu, kemudian",
          "oleh karena itu, sehingga, sebab",
          "meskipun demikian, akan tetapi",
          "bahkan, lagipula",
          "sebelumnya, setelah itu"
        ],
        kunciJawaban: 1,
        pembahasan: "Konjungsi kausalitas menyatakan hubungan sebab-akibat, seperti: sebab, karena, oleh karena itu, oleh sebab itu, dan sehingga.",
        poinDefault: 15,
      },
    ],
  },
  {
    id: "pkt-bs-06",
    kode: "PKT-ING-01",
    judul: "Bank Soal Bahasa Inggris: Passive Voice in Academic Context",
    deskripsi: "Penguasaan kaidah kalimat pasif dalam laporan ilmiah dan ketepatan tenses Simple Present.",
    mapel: "Bahasa Inggris",
    tingkatKelas: "XI",
    topik: "Passive Voice in Academic Context",
    pembuatGuru: "Ahmad Fauzi, S.Pd.",
    createdAt: "2025-08-08",
    soalList: [
      {
        id: "bs-12",
        kode: "BS-ING-01",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Choose the correct passive form: 'Scientists conduct extensive experiments in the laboratory every month.'",
        pilihan: [
          "Extensive experiments are conducted by scientists in the laboratory every month.",
          "Extensive experiments were conducted by scientists in the laboratory every month.",
          "Extensive experiments are conducting by scientists in the laboratory every month.",
          "Extensive experiments have been conducted by scientists in the laboratory every month.",
          "Extensive experiments will be conducted by scientists in the laboratory every month."
        ],
        kunciJawaban: 0,
        pembahasan: "Active sentence is in Simple Present Tense (conduct). The passive pattern for simple present is: Subject + am/is/are + Past Participle (V3). Because 'experiments' is plural, we use 'are conducted'.",
        poinDefault: 15,
      },
    ],
  },
  {
    id: "pkt-bs-k6",
    kode: "PKT-SD6-01",
    judul: "Bank Soal Tematik & Matematika Dasar Kelas 6",
    deskripsi: "Koleksi butir soal terstandar materi bilangan pecahan, bangun ruang, dan ekosistem makhluk hidup kelas 6.",
    mapel: "Matematika",
    tingkatKelas: "6",
    topik: "Bilangan Pecahan, Desimal & Ekosistem",
    pembuatGuru: "Ahmad Fauzi, S.Pd.I.",
    createdAt: "2025-08-04",
    soalList: [
      {
        id: "bs-k6-01",
        kode: "BS-K6-01",
        tingkatKesulitan: "Mudah",
        pertanyaan: "Bentuk desimal dari pecahan 3/8 adalah...",
        pilihan: ["0.375", "0.38", "0.35", "0.425", "0.625"],
        kunciJawaban: 0,
        pembahasan: "3 dibagi 8 = 0.375.",
        poinDefault: 10,
      },
      {
        id: "bs-k6-02",
        kode: "BS-K6-02",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Sebuah akuarium berbentuk balok berukuran panjang 60 cm, lebar 40 cm, dan tinggi 50 cm. Volume akuarium tersebut dalam liter adalah...",
        pilihan: ["120 Liter", "12 Liter", "1200 Liter", "60 Liter", "240 Liter"],
        kunciJawaban: 0,
        pembahasan: "Volume = 60 × 40 × 50 = 120.000 cm³ = 120 dm³ = 120 Liter.",
        poinDefault: 15,
      },
      {
        id: "bs-k6-03",
        kode: "BS-K6-03",
        tingkatKesulitan: "Sedang",
        pertanyaan: "Hubungan simbiosis mutualisme terjadi pada interaksi antara...",
        pilihan: [
          "Ikan hiu dengan ikan remora",
          "Kutu dengan rambut manusia",
          "Lebah madu dengan bunga tanaman",
          "Tanaman anggrek dengan pohon mangga",
          "Tali putri dengan tanaman inangnya"
        ],
        kunciJawaban: 2,
        pembahasan: "Lebah mendapatkan nektar dari bunga, sedangkan bunga terbantu dalam proses penyerbukan (saling menguntungkan / mutualisme).",
        poinDefault: 15,
      },
    ],
  },
];

export const INITIAL_LMS_JADWAL_MATERI: LMSJadwalMateri[] = [
  // --- MINGGU 1 (01 - 06 September 2025) ---
  {
    id: "jdw-mat-01",
    mingguKe: 1,
    rentangTanggal: "01 - 06 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Matematika",
    kelas: "Kelas 6",
    bab: "Bab 1: Operasi Hitung Pecahan & Desimal",
    subBab: [
      "1.1 Penjumlahan & Pengurangan Pecahan Biasa dan Campuran",
      "1.2 Perkalian Pecahan Campuran dengan Desimal",
      "1.3 Pemecahan Masalah Kontekstual Keuangan Sehari-hari"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri mampu mengalikan pecahan campuran dan menyelesaikan soal cerita dengan akurat.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-02",
    jamRealisasi: "07.30 - 09.00 WIB",
    guruPengajar: "Siti Nurhaliza, S.Pd., M.Si.",
    guruId: "usr-guru",
    catatanPembelajaran: "Alhamdulillah santri antusias, 90% santri menguasai konsep perkalian pecahan campuran.",
  },
  {
    id: "jdw-mat-02",
    mingguKe: 1,
    rentangTanggal: "01 - 06 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Pendidikan Agama Islam",
    kelas: "Kelas 6",
    bab: "Bab 1: Meneladani Asmaul Husna (As-Samad & Al-Muqtadir)",
    subBab: [
      "1.1 Makna Asmaul Husna As-Samad Beserta Dalil Naqli",
      "1.2 Memahami Keagungan Sifat Al-Muqtadir di Alam Semesta",
      "1.3 Penerapan Perilaku Mandiri dan Bergantung Hanya Kepada Allah"
    ],
    alokasiJP: 3,
    indikatorKompetensi: "Santri mampu melafalkan Asmaul Husna dengan tartil dan menguraikan hikmahnya.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-03",
    jamRealisasi: "09.30 - 11.00 WIB",
    guruPengajar: "Ust. Ahmad Fauzi, S.Pd.I.",
    guruId: "usr-guru-fauzi",
    catatanPembelajaran: "Seluruh santri hafal dalil dan artinya. Dilakukan kuis lisan santri beregu.",
  },
  {
    id: "jdw-mat-03",
    mingguKe: 1,
    rentangTanggal: "01 - 06 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Bahasa Arab",
    kelas: "Kelas 6",
    bab: "Bab 1: Fiil Madhi & Peralatan Belajar di Madrasah (Al-Adawatul Madrasiyyah)",
    subBab: [
      "1.1 Mufradat Kosa Kata Perlengkapan Belajar",
      "1.2 Tashrif Lughawi Fiil Madhi Dhomir Huwa, Hiya, Anta, Ana",
      "1.3 Praktik Percakapan Singkat (Hiwar) Dua Santri"
    ],
    alokasiJP: 2,
    indikatorKompetensi: "Santri mampu merangkai kalimat sempurna menggunakan fiil madhi.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-04",
    jamRealisasi: "08.00 - 09.30 WIB",
    guruPengajar: "Ust. Zulkifli Mansur, Lc.",
    catatanPembelajaran: "Praktik dialog hiwar berjalan lancar dan interaktif.",
  },
  {
    id: "jdw-mat-04",
    mingguKe: 1,
    rentangTanggal: "01 - 06 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Tematik",
    kelas: "Kelas 6",
    bab: "Bab 1: Perkembangbiakan Generatif & Vegetatif Tumbuhan",
    subBab: [
      "1.1 Struktur Bunga Sempurna & Proses Penyerbukan",
      "1.2 Perkembangbiakan Vegetatif Alami (Tunas, Umbi, Spora)",
      "1.3 Praktik Observasi Tumbuhan di Taman Sekolah"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri mampu mengidentifikasi cara perkembangbiakan tanaman sekitar.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-05",
    jamRealisasi: "07.30 - 09.30 WIB",
    guruPengajar: "Dewi Kurniasih, S.Si., M.Pd.",
    catatanPembelajaran: "Observasi langsung di kebun sekolah sangat membantu pemahaman visual santri.",
  },

  // --- MINGGU 2 (08 - 13 September 2025) ---
  {
    id: "jdw-mat-05",
    mingguKe: 2,
    rentangTanggal: "08 - 13 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Matematika",
    kelas: "Kelas 6",
    bab: "Bab 2: Operasi Hitung Bilangan Bulat Negatif",
    subBab: [
      "2.1 Membaca & Menulis Lambang Bilangan Bulat pada Garis Bilangan",
      "2.2 Operasi Penjumlahan Bilangan Bulat Positif dan Negatif",
      "2.3 Operasi Pengurangan Bilangan Bulat Menggunakan Garis Bilangan"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri memahami konsep hutang-piutang dan koordinat garis bilangan.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-09",
    jamRealisasi: "07.30 - 09.00 WIB",
    guruPengajar: "Siti Nurhaliza, S.Pd., M.Si.",
    catatanPembelajaran: "Sebagian santri awalnya bingung konsep tanda minus bertemu minus, setelah analogi tangga semua paham.",
  },
  {
    id: "jdw-mat-06",
    mingguKe: 2,
    rentangTanggal: "08 - 13 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Pendidikan Agama Islam",
    kelas: "Kelas 6",
    bab: "Bab 2: Fiqih Shalat Berjamaah, Jamak & Qashar",
    subBab: [
      "2.1 Keutamaan & Adab Shalat Berjamaah di Masjid",
      "2.2 Syarat dan Ketentuan Shalat Jamak Taqdim & Takhir",
      "2.3 Keringanan Rukhsah Shalat Qashar bagi Musafir"
    ],
    alokasiJP: 3,
    indikatorKompetensi: "Santri mempraktikkan niat dan tata cara shalat jamak dan qashar.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-10",
    jamRealisasi: "09.30 - 11.00 WIB",
    guruPengajar: "Ust. Ahmad Fauzi, S.Pd.I.",
    catatanPembelajaran: "Praktik simulasi safar dan shalat jamak qashar langsung dipraktikkan di Musholla SDI.",
  },
  {
    id: "jdw-mat-07",
    mingguKe: 2,
    rentangTanggal: "08 - 13 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Bahasa Indonesia",
    kelas: "Kelas 6",
    bab: "Bab 2: Menulis Teks Formulir dan Petunjuk Teknis",
    subBab: [
      "2.1 Bagian-bagian Formulir Pendaftaran, Wesel Pos, dan Ujian",
      "2.2 Menyusun Langkah Petunjuk Penggunaan Barang yang Runtut"
    ],
    alokasiJP: 3,
    indikatorKompetensi: "Santri dapat mengisi formulir resmi secara teliti dan benar.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-11",
    jamRealisasi: "08.00 - 09.30 WIB",
    guruPengajar: "Hj. Ratna Dewi, S.Pd.I., M.Ag.",
    catatanPembelajaran: "Semua santri berhasil mengisi form pendaftaran ekskul dengan data valid.",
  },

  // --- MINGGU 3 (15 - 20 September 2025 - PEKAN INI) ---
  {
    id: "jdw-mat-08",
    mingguKe: 3,
    rentangTanggal: "15 - 20 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Matematika",
    kelas: "Kelas 6",
    bab: "Bab 3: Unsur-unsur Lingkaran & Luas Daerah",
    subBab: [
      "3.1 Titik Pusat, Jari-jari (r), Diameter (d), Busur, Tali Busur, dan Juring",
      "3.2 Menemukan Pendekatan Nilai Pi (π = 22/7 atau 3.14)",
      "3.3 Rumus dan Perhitungan Keliling Lingkaran",
      "3.4 Rumus dan Perhitungan Luas Daerah Lingkaran Penuh & Sebagian"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri mampu menghitung keliling dan luas lingkaran serta menyelesaikan masalah terkait benda bundar.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-16",
    jamRealisasi: "08.00 - 09.30 WIB",
    guruPengajar: "Siti Nurhaliza, S.Pd., M.Si.",
    guruId: "usr-guru",
    catatanPembelajaran: "Santri telah paham unsur lingkaran, sebagian masih memerlukan pendampingan hitung pecahan desimal perkalian π = 3.14.",
  },
  {
    id: "jdw-mat-09",
    mingguKe: 3,
    rentangTanggal: "15 - 20 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Pendidikan Agama Islam",
    kelas: "Kelas 6",
    bab: "Bab 3: Kisah Teladan Khulafaur Rasyidin (Khalifah Abu Bakar Ash-Shiddiq)",
    subBab: [
      "3.1 Riwayat Singkat & Gelar Kemuliaan Ash-Shiddiq",
      "3.2 Kesetiaan & Pengorbanan Menemani Hijrah Rasulullah SAW di Gua Tsur",
      "3.3 Ketegasan Kepemimpinan Menghadapi Kaum Pembangkang Zakat dan Nabi Palsu"
    ],
    alokasiJP: 3,
    indikatorKompetensi: "Santri mampu meneladani sifat jujur, dermawan, dan teguh pendirian Khalifah Abu Bakar RA.",
    sudahDiajarkan: true,
    tanggalRealisasi: "2025-09-17",
    jamRealisasi: "09.30 - 11.00 WIB",
    guruPengajar: "Ust. Ahmad Fauzi, S.Pd.I.",
    guruId: "usr-guru-fauzi",
    catatanPembelajaran: "Santri sangat khusyuk menyimak kisah kedermawanan Abu Bakar yang menyerahkan seluruh hartanya di jalan Allah.",
  },
  {
    id: "jdw-mat-10",
    mingguKe: 3,
    rentangTanggal: "15 - 20 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Bahasa Arab",
    kelas: "Kelas 6",
    bab: "Bab 2: Jam & Waktu Aktivitas Harian (As-Saa'ah)",
    subBab: [
      "2.1 Menyebutkan Jam 1 sampai Jam 12 dalam Bilangan Bertingkat Arab",
      "2.2 Penggunaan Istilah Lebih (Wa), Kurang (Illa), Setengah (Nisfun), dan Seperempat (Rub'un)",
      "2.3 Menyusun Kalimat Tanya Waktu (Kamis-Saa'atul Aan?) dan Waktu Ibadah Shalat"
    ],
    alokasiJP: 2,
    indikatorKompetensi: "Santri mampu bertanya dan menjawab waktu dalam bahasa Arab dengan fasih.",
    sudahDiajarkan: false,
    catatanPembelajaran: "",
  },
  {
    id: "jdw-mat-11",
    mingguKe: 3,
    rentangTanggal: "15 - 20 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Tematik",
    kelas: "Kelas 6",
    bab: "Bab 2: Adaptasi Fisiologi & Morfologi Makhluk Hidup",
    subBab: [
      "2.1 Cara Hewan Menyesuaikan Diri dengan Habitatnya (Kamuslase, Mimikri, Autotomi)",
      "2.2 Adaptasi Tumbuhan Xerofit, Hidrofit, dan Higrofit",
      "2.3 Perlindungan Diri Makhluk Hidup dari Pemangsa Alami"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri dapat mengklasifikasikan adaptasi tumbuhan teratai, kaktus, dan kantong semar.",
    sudahDiajarkan: false,
    catatanPembelajaran: "",
  },

  // --- MINGGU 4 (22 - 27 September 2025) ---
  {
    id: "jdw-mat-12",
    mingguKe: 4,
    rentangTanggal: "22 - 27 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Matematika",
    kelas: "Kelas 6",
    bab: "Bab 4: Bangun Ruang Sisi Datar & Luas Permukaan",
    subBab: [
      "4.1 Mengidentifikasi Sifat Rusuk, Titik Sudut, dan Sisi Kubus & Balok",
      "4.2 Jaring-jaring Kubus dan Balok Melalui Pola Lipat Kertas",
      "4.3 Menghitung Luas Permukaan Kubus dan Balok"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri terampil menggambar jaring-jaring bangun ruang.",
    sudahDiajarkan: false,
  },
  {
    id: "jdw-mat-13",
    mingguKe: 4,
    rentangTanggal: "22 - 27 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Pendidikan Agama Islam",
    kelas: "Kelas 6",
    bab: "Bab 4: Akhlak Terpuji Bersyukur & Sifat Qana'ah",
    subBab: [
      "4.1 Hakikat Rasa Syukur Melalui Hati, Lisan (Tahmid), dan Amal Perbuatan",
      "4.2 Keutamaan Qana'ah Merasa Cukup dengan Karunia Rezeki Halal",
      "4.3 Bahaya Sikap Kufur Nikmat, Tamak, dan Hasad dalam Pergaulan"
    ],
    alokasiJP: 3,
    indikatorKompetensi: "Santri membiasakan ungkapan syukur dan tidak mengeluh.",
    sudahDiajarkan: false,
  },
  {
    id: "jdw-mat-14",
    mingguKe: 4,
    rentangTanggal: "22 - 27 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Bahasa Arab",
    kelas: "Kelas 6",
    bab: "Bab 3: Hobi dan Kegemaran Santri (Al-Hiwayah)",
    subBab: [
      "3.1 Mufradat Jenis Hobi (Qira'ah, Riasah, Tashwir, Rasm)",
      "3.2 Menyusun Paragraf Sederhana tentang Cita-cita dan Kegemaran"
    ],
    alokasiJP: 2,
    indikatorKompetensi: "Santri dapat menceritakan kegemaran dalam bahasa Arab.",
    sudahDiajarkan: false,
  },
  {
    id: "jdw-mat-15",
    mingguKe: 4,
    rentangTanggal: "22 - 27 September 2025",
    bulan: "September",
    semester: "Ganjil",
    tahunAjaran: "2025/2026",
    mapel: "Tematik",
    kelas: "Kelas 6",
    bab: "Bab 3: Tokoh Penemu dan Pengaruhnya bagi Peradaban Dunia",
    subBab: [
      "3.1 Penemu Listrik Michael Faraday & Rangkaian Seri-Paralel",
      "3.2 Dampak Penemuan Teknologi terhadap Kehidupan Sosial & Ekonomi",
      "3.3 Praktik Merangkai Lampu Senter Sederhana"
    ],
    alokasiJP: 4,
    indikatorKompetensi: "Santri memahami rangkaian listrik seri dan paralel.",
    sudahDiajarkan: false,
  },
];



// =========================================================
// DATA MASTER 37 SURAH JUZ 30 (AN-NABA' s.d. AN-NAS)
// =========================================================

export const SURAH_JUZ_30: SurahJuz30Info[] = [
  { nomorSurah: 78, namaLatin: "An-Naba'", namaArab: "النبأ", arti: "Berita Besar", jumlahAyat: 40, tempatTurun: "Makkah" },
  { nomorSurah: 79, namaLatin: "An-Nazi'at", namaArab: "النازعات", arti: "Malaikat Pencabut", jumlahAyat: 46, tempatTurun: "Makkah" },
  { nomorSurah: 80, namaLatin: "'Abasa", namaArab: "عبس", arti: "Ia Bermuka Masam", jumlahAyat: 42, tempatTurun: "Makkah" },
  { nomorSurah: 81, namaLatin: "At-Takwir", namaArab: "التكوير", arti: "Menggulung", jumlahAyat: 29, tempatTurun: "Makkah" },
  { nomorSurah: 82, namaLatin: "Al-Infitar", namaArab: "الانفطار", arti: "Terbelah", jumlahAyat: 19, tempatTurun: "Makkah" },
  { nomorSurah: 83, namaLatin: "Al-Muthaffifin", namaArab: "المطففين", arti: "Orang Curang", jumlahAyat: 36, tempatTurun: "Makkah" },
  { nomorSurah: 84, namaLatin: "Al-Insyiqaq", namaArab: "الانشقاق", arti: "Terbelah", jumlahAyat: 25, tempatTurun: "Makkah" },
  { nomorSurah: 85, namaLatin: "Al-Buruj", namaArab: "البروج", arti: "Gugusan Bintang", jumlahAyat: 22, tempatTurun: "Makkah" },
  { nomorSurah: 86, namaLatin: "At-Tariq", namaArab: "الطارق", arti: "Yang Datang di Malam Hari", jumlahAyat: 17, tempatTurun: "Makkah" },
  { nomorSurah: 87, namaLatin: "Al-A'la", namaArab: "الأعلى", arti: "Yang Maha Tinggi", jumlahAyat: 19, tempatTurun: "Makkah" },
  { nomorSurah: 88, namaLatin: "Al-Ghasyiyah", namaArab: "الغاشية", arti: "Hari Pembalasan", jumlahAyat: 26, tempatTurun: "Makkah" },
  { nomorSurah: 89, namaLatin: "Al-Fajr", namaArab: "الفجر", arti: "Fajar", jumlahAyat: 30, tempatTurun: "Makkah" },
  { nomorSurah: 90, namaLatin: "Al-Balad", namaArab: "البلد", arti: "Negeri", jumlahAyat: 20, tempatTurun: "Makkah" },
  { nomorSurah: 91, namaLatin: "Asy-Syams", namaArab: "الشمس", arti: "Matahari", jumlahAyat: 15, tempatTurun: "Makkah" },
  { nomorSurah: 92, namaLatin: "Al-Lail", namaArab: "الليل", arti: "Malam", jumlahAyat: 21, tempatTurun: "Makkah" },
  { nomorSurah: 93, namaLatin: "Adh-Dhuha", namaArab: "الضحى", arti: "Waktu Dhuha", jumlahAyat: 11, tempatTurun: "Makkah" },
  { nomorSurah: 94, namaLatin: "Al-Insyirah", namaArab: "الشرح", arti: "Kelapangan", jumlahAyat: 8, tempatTurun: "Makkah" },
  { nomorSurah: 95, namaLatin: "At-Tin", namaArab: "التين", arti: "Buah Tin", jumlahAyat: 8, tempatTurun: "Makkah" },
  { nomorSurah: 96, namaLatin: "Al-'Alaq", namaArab: "العلق", arti: "Segumpal Darah", jumlahAyat: 19, tempatTurun: "Makkah" },
  { nomorSurah: 97, namaLatin: "Al-Qadr", namaArab: "القدر", arti: "Kemuliaan", jumlahAyat: 5, tempatTurun: "Makkah" },
  { nomorSurah: 98, namaLatin: "Al-Bayyinah", namaArab: "البينة", arti: "Bukti Nyata", jumlahAyat: 8, tempatTurun: "Madinah" },
  { nomorSurah: 99, namaLatin: "Az-Zalzalah", namaArab: "الزلزلة", arti: "Keguncangan", jumlahAyat: 8, tempatTurun: "Madinah" },
  { nomorSurah: 100, namaLatin: "Al-'Adiyat", namaArab: "العاديات", arti: "Kuda Perang Berlari Kencang", jumlahAyat: 11, tempatTurun: "Makkah" },
  { nomorSurah: 101, namaLatin: "Al-Qari'ah", namaArab: "القارعة", arti: "Hari Kiamat", jumlahAyat: 11, tempatTurun: "Makkah" },
  { nomorSurah: 102, namaLatin: "At-Takatsur", namaArab: "التكاثر", arti: "Bermegah-megahan", jumlahAyat: 8, tempatTurun: "Makkah" },
  { nomorSurah: 103, namaLatin: "Al-'Asr", namaArab: "العصر", arti: "Masa", jumlahAyat: 3, tempatTurun: "Makkah" },
  { nomorSurah: 104, namaLatin: "Al-Humazah", namaArab: "الهمزة", arti: "Pengumpat", jumlahAyat: 9, tempatTurun: "Makkah" },
  { nomorSurah: 105, namaLatin: "Al-Fil", namaArab: "الفيل", arti: "Gajah", jumlahAyat: 5, tempatTurun: "Makkah" },
  { nomorSurah: 106, namaLatin: "Quraisy", namaArab: "قريش", arti: "Suku Quraisy", jumlahAyat: 4, tempatTurun: "Makkah" },
  { nomorSurah: 107, namaLatin: "Al-Ma'un", namaArab: "الماعون", arti: "Barang Berguna", jumlahAyat: 7, tempatTurun: "Makkah" },
  { nomorSurah: 108, namaLatin: "Al-Kautsar", namaArab: "الكوثر", arti: "Nikmat Berlimpah", jumlahAyat: 3, tempatTurun: "Makkah" },
  { nomorSurah: 109, namaLatin: "Al-Kafirun", namaArab: "الكافرون", arti: "Orang Kafir", jumlahAyat: 6, tempatTurun: "Makkah" },
  { nomorSurah: 110, namaLatin: "An-Nashr", namaArab: "النصر", arti: "Pertolongan", jumlahAyat: 3, tempatTurun: "Madinah" },
  { nomorSurah: 111, namaLatin: "Al-Lahab", namaArab: "المسد", arti: "Gejolak Api", jumlahAyat: 5, tempatTurun: "Makkah" },
  { nomorSurah: 112, namaLatin: "Al-Ikhlas", namaArab: "الإخلاص", arti: "Memurnikan Keesaan Allah", jumlahAyat: 4, tempatTurun: "Makkah" },
  { nomorSurah: 113, namaLatin: "Al-Falaq", namaArab: "الفلق", arti: "Waktu Subuh", jumlahAyat: 5, tempatTurun: "Makkah" },
  { nomorSurah: 114, namaLatin: "An-Nas", namaArab: "الناس", arti: "Manusia", jumlahAyat: 6, tempatTurun: "Makkah" },
];

// =========================================================
// INITIAL DATA TAHFIDZ SISWA (JURNAL HAFALAN AL-QUR'AN)
// =========================================================

export const INITIAL_TAHFIDZ_RECORDS: TahfidzRecord[] = [
  {
    id: "thf-001",
    siswaId: "sis-001",
    siswaNama: "Muhammad Farhan Al-Fatih",
    nisn: "0081234567",
    kelas: "Kelas 4A",
    tanggal: "2026-09-19",
    jenisSetoran: "Ziyadah (Hafalan Baru)",
    juz: 30,
    surah: "An-Naba'",
    ayatMulai: 1,
    ayatSelesai: 20,
    halaman: 582,
    kelancaran: "Mutqin (Sangat Lancar)",
    nilaiMakhraj: 94,
    nilaiTajwid: 92,
    catatanUstadz: "Makharijul huruf 'Ain dan Ha sangat bersih. Dengung ikhfa haqiqi terjaga dengan baik. Lanjutkan ayat 21-40.",
    ustadzPengampu: "Ustadz Ahmad Fauzi, Lc., S.Pd.I.",
    ustadzId: "usr-guru-fauzi",
    createdAt: "2026-09-19T08:30:00Z",
  },
  {
    id: "thf-002",
    siswaId: "sis-001",
    siswaNama: "Muhammad Farhan Al-Fatih",
    nisn: "0081234567",
    kelas: "Kelas 4A",
    tanggal: "2026-09-17",
    jenisSetoran: "Muraja'ah (Mengulang)",
    juz: 30,
    surah: "An-Nazi'at",
    ayatMulai: 1,
    ayatSelesai: 46,
    halaman: 583,
    kelancaran: "Jayyid Jiddan (Lancar Sekali)",
    nilaiMakhraj: 90,
    nilaiTajwid: 88,
    catatanUstadz: "Alhamdulillah surah An-Nazi'at selesai dengan predikat Jayyid Jiddan.",
    ustadzPengampu: "Ustadz Ahmad Fauzi, Lc., S.Pd.I.",
    ustadzId: "usr-guru-fauzi",
    createdAt: "2026-09-17T08:15:00Z",
  },
  {
    id: "thf-003",
    siswaId: "sis-002",
    siswaNama: "Aisyah Azzahra",
    nisn: "0081234568",
    kelas: "Kelas 4A",
    tanggal: "2026-09-19",
    jenisSetoran: "Ujian Tasmi'",
    juz: 30,
    surah: "Al-A'la",
    ayatMulai: 1,
    ayatSelesai: 19,
    halaman: 591,
    kelancaran: "Mutqin (Sangat Lancar)",
    nilaiMakhraj: 96,
    nilaiTajwid: 95,
    catatanUstadz: "Mumtaz! Bacaan bertajwid dan berirama tartil. Lulus tasmi' Surah Al-A'la.",
    ustadzPengampu: "Ustadzah Hj. Ratna Dewi, M.Ag.",
    ustadzId: "usr-guru-ratna",
    createdAt: "2026-09-19T09:00:00Z",
  },
  {
    id: "thf-004",
    siswaId: "sis-003",
    siswaNama: "Rayhan Putra Pratama",
    nisn: "0081234569",
    kelas: "Kelas 4B",
    tanggal: "2026-09-18",
    jenisSetoran: "Ziyadah (Hafalan Baru)",
    juz: 30,
    surah: "At-Takwir",
    ayatMulai: 1,
    ayatSelesai: 15,
    halaman: 586,
    kelancaran: "Jayyid (Lancar)",
    nilaiMakhraj: 85,
    nilaiTajwid: 84,
    catatanUstadz: "Perhatikan panjang mad wajib muttashil pada ayat 10-14.",
    ustadzPengampu: "Ustadz Ahmad Fauzi, Lc., S.Pd.I.",
    ustadzId: "usr-guru-fauzi",
    createdAt: "2026-09-18T08:45:00Z",
  },
  {
    id: "thf-005",
    siswaId: "sis-004",
    siswaNama: "Siti Nabila Khairunnisa",
    nisn: "0081234570",
    kelas: "Kelas 4B",
    tanggal: "2026-09-19",
    jenisSetoran: "Ziyadah (Hafalan Baru)",
    juz: 30,
    surah: "Adh-Dhuha",
    ayatMulai: 1,
    ayatSelesai: 11,
    halaman: 596,
    kelancaran: "Mutqin (Sangat Lancar)",
    nilaiMakhraj: 95,
    nilaiTajwid: 94,
    catatanUstadz: "Masya Allah, hafalan lancar tanpa jeda. Siap lanjut Surah Al-Lail.",
    ustadzPengampu: "Ustadzah Hj. Ratna Dewi, M.Ag.",
    ustadzId: "usr-guru-ratna",
    createdAt: "2026-09-19T09:20:00Z",
  },
];

// =========================================================
// INITIAL DATA MUTABA'AH YAUMIYAH (IBADAH HARIAN SISWA)
// =========================================================

export const INITIAL_MUTABAAH_RECORDS: MutabaahRecord[] = [
  {
    id: "mtb-001",
    siswaId: "sis-001",
    siswaNama: "Muhammad Farhan Al-Fatih",
    nisn: "0081234567",
    kelas: "Kelas 4A",
    tanggal: "2026-09-19",
    shalatWajib: {
      subuh: "Ya",
      dzuhur: "Ya",
      ashar: "Ya",
      maghrib: "Ya",
      isya: "Ya",
    },
    ibadahSunnah: {
      shalatDhuha: true,
      rawatib: true,
      tilawahQuran: true,
      jumlahHalamanTilawah: 2,
    },
    akhlakKarakter: {
      birrulWalidain: true,
      belajarMandiri: true,
    },
    catatanOrangTua: "Alhamdulillah Farhan hari ini shalat 5 waktu tertib dan membantu orang tua.",
    skorKebaikan: 100,
    statusVerifikasi: "Diberi Bintang Kebaikan",
    catatanGuru: "Masya Allah tabarakallah, istiqamah selalu ya Farhan! ⭐⭐⭐",
    verifiedByGuru: "Ustadz Ahmad Fauzi, Lc.",
    createdAt: "2026-09-19T20:30:00Z",
  },
  {
    id: "mtb-002",
    siswaId: "sis-002",
    siswaNama: "Aisyah Azzahra",
    nisn: "0081234568",
    kelas: "Kelas 4A",
    tanggal: "2026-09-19",
    shalatWajib: {
      subuh: "Ya",
      dzuhur: "Ya",
      ashar: "Ya",
      maghrib: "Ya",
      isya: "Ya",
    },
    ibadahSunnah: {
      shalatDhuha: true,
      rawatib: true,
      tilawahQuran: true,
      jumlahHalamanTilawah: 3,
    },
    akhlakKarakter: {
      birrulWalidain: true,
      belajarMandiri: true,
    },
    catatanOrangTua: "Aisyah rajin membaca Al-Qur'an setelah Maghrib dan belajar mandiri.",
    skorKebaikan: 100,
    statusVerifikasi: "Diberi Bintang Kebaikan",
    catatanGuru: "Shalihah Aisyah! Terus jaga shalat tepat waktu dan birrul walidain ya nak. ⭐",
    verifiedByGuru: "Ustadzah Hj. Ratna Dewi",
    createdAt: "2026-09-19T20:45:00Z",
  },
  {
    id: "mtb-003",
    siswaId: "sis-003",
    siswaNama: "Rayhan Putra Pratama",
    nisn: "0081234569",
    kelas: "Kelas 4B",
    tanggal: "2026-09-19",
    shalatWajib: {
      subuh: "Ya",
      dzuhur: "Ya",
      ashar: "Ya",
      maghrib: "Ya",
      isya: "Tidak",
    },
    ibadahSunnah: {
      shalatDhuha: true,
      rawatib: false,
      tilawahQuran: true,
      jumlahHalamanTilawah: 1,
    },
    akhlakKarakter: {
      birrulWalidain: true,
      belajarMandiri: true,
    },
    catatanOrangTua: "Rayhan hari ini tertidur saat Isya, besok ditingkatkan lagi.",
    skorKebaikan: 80,
    statusVerifikasi: "Terverifikasi Guru",
    catatanGuru: "Bagus Rayhan, jangan lupa shalat Isya tepat waktu ya!",
    verifiedByGuru: "Ustadz Ahmad Fauzi, Lc.",
    createdAt: "2026-09-19T21:00:00Z",
  },
];
